### ISSUE TITLE
Improved instruction selection for JumpIf Imm

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#104]
When the immediate value is too large, the instruction selection drops the immediate into a normal register. This consumes a register name, which is bad because it might mean that some other value gets pushed onto the stack.

An alternative strategy is to wait until the word-to-stack compiler and have it drop the too large immediate into one of its temporaries so that a normal register isn't wasted on this short-lived immediate value.

**Comment by tanyongkiam** [comment]
This is about moving this particular case split into `word_to_stack` instead:

https://github.com/CakeML/cakeml/blob/8c68847abd8fee8b25a2e9fbacd3a2089f6e986d/compiler/backend/word_instScript.sml#L388

**Comment by tanyongkiam** [comment]
This is closed by #1038
