### ISSUE TITLE
Distribute stackLang (and possibly other languages') syntactic invariant proofs into their own files 

### ISSUE THREAD

**Issue by tanyongkiam** [CakeML/cakeml#108]
Currently, half of them gets proved inside backendProof (namely the ones that are all called good_syntax) and half gets proved inside the individual files (namely the ongoing label preservation proofs in fix_backendProof).

**Comment by xrchz** [comment]
To be clear, I think these proofs should happen in the existing compiler proof scripts for the individual phases (not in `backendProof` and not in any new theories). @tanyongkiam, what is the status?

**Comment by tanyongkiam** [comment]
I haven't looked at this, but I made this issue to refer to the bunch of quick syntactic proofs I wrote here:
https://github.com/CakeML/cakeml/blob/master/compiler/backend/proofs/backendProofScript.sml#L233

The main annoying thing is that the good_syntax-es are currently defined in their own proof scripts e.g. in stack_removeProof, stack_allocProof. However, they also need to be accessed in the other proof scripts. I don't want to make the proofs inherit from each other.

The way I get around this for wordLang is to move all the syntactic stuff into wordProps. However, this would be a bigger change for stackLang (because good_syntax has to be renamed).

**Comment by xrchz** [comment]
I think the syntactic predicates should be defined in `stackProps` and not in the `Proof` scripts. And I agree that these proofs should move out of `backendProof`. Why would there need to be a rename?

**Comment by tanyongkiam** [comment]
There needs to be a rename because all of them are called good_syntax, and defined in their own respective proof scripts at the moment.

It doesn't seem right to put them in stackProps though.

**Comment by xrchz** [comment]
Are they all predicates on `stackLang` programs? Are they accessed by `stackXProof` theories? If so then `stackProps` does seem like the right place.

**Comment by tanyongkiam** [comment]
Closed by commit 048b787
