### ISSUE TITLE
Bignum support in asm

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#109]
The asm instructions need to include the following in order for the bignum implementation (in wordLang stubs) to make use of special-purpose hardware instructions that make it go at reasonable speed.
- **add-with-carry-in-and-carry-out** takes three registers as input, one of which must be either 0 or 1, updates two registers with the result of adding all three inputs registers.
- **multiply** takes two registers as input, multiplies them and updates two registers with the full result of the multiplication.
- **division-long** takes three registers as input `i1`, `i2`, `j`, stores `w2n (i1*dimindex(:'a) + i2) DIV w2n j` and `w2n (i1*dimindex(:'a) + i2) MOD w2n j` into two output registers. The semantics can assert that `j` is not 0 and that `w2n (i1*dimindex(:'a) + i2) DIV w2n j` is less than `dimindex(:'a)`.
- **division** takes two input registers `i`, `j` and updates one register with the value of `w2n i DIV w2n j`. The semantics can assert that `j` is not 0. 

Note that **division** and **division-long** are optional, and the compiler will never use **division** for architectures where **division-long** is present.

Instructions **multiply**, **division** and **division-long** are allowed to require that some of their inputs/outputs must be in specific registers. These constraints are to be recorded in the asm configuration along with the availability information for **division** and **division-long**.

All operations are to have unsigned semantics.

**Comment by tanyongkiam** [comment]
Will these specific registers all be usable for general purpose compute as well? Can they be treated like an ordinary register for other purposes?

**Comment by myreen** [comment]
They are ordinary registers. They just happen to be fixed to a specific register for certain instructions.

**Comment by tanyongkiam** [comment]
Recording here before I forget:

The register allocation phase needs to be extended to support explicit inequality constraints that arise in these new instructions for different architectures (e.g. AddCarry ((c.ISA_name = "MIPS") \/  (c.ISA_name = "RISC-V")) ==> r1 <> r3 /\ r1 <> r4)).

This could be done by adding the appropriate edges to the clash graph.

**Comment by tanyongkiam** [comment]
Recording another things that was previously in dev emails:

AddCarry is currently forced to have r4 be in register 0. This avoids a situation where three spills can arise (if r2 r3 r4 are all spilled).

**Comment by tanyongkiam** [comment]
In 06a8dff I forced the conventions to make AddCarry take the form: AddCarry 4 _ 2 0 so that the above inequality constraint is trivially satisfied.
LongMul and LongDiv are also forced into their respective required forms (LongMul 2 0 0 _ and LongDiv 0 2 0 2 _)

**Comment by xrchz** [comment]
I think this is now done. As of 980b42efb0056481a3ab19ac00e49d50bad58379 I think all the originally requested operations have been added. (By commits like dce0c421863e2397b1b8f4fb7a9e9ee086120b14 and 88e71a6cbdc7b8577937af9450d85aca47a4e669.)
