### ISSUE TITLE
Add missing directories to build-sequence

### ISSUE THREAD

**Issue by dnezam** [CakeML/cakeml#1095]
At the moment, it appears that there are some directories that contain a Holmakefile, but are not mentioned in `developers/build-sequence` and hence not part of the regression suite. This lead to some directories having bit-rotted away.

The goal of this issue is to add all missing directories to `build-sequence`. If some directories cannot be built, they should either be fixed or removed*, potentially creating an issue if there is demand to add it back in the future.

For the future, ideally a linter would make sure that no directory can slip past the regression suite.

\* Exceptions may apply.

**Comment by xrchz** [comment]
There's apparently something called `check_builds` in HOL4 that does the linting thing
