### ISSUE TITLE
Automatic benchmark report

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#110]
It would be good if we could produce a benchmark report automatically by some call to Holmake, say Holmake benchmark.txt. With such a facility it would be easy to measure the impact of any adjustments to the compiler implementation. I'm particularly interested in this now, because I'm about to implement call-intro and related closLang optimisations.

Initially the benchmark programs could just be the ones we've used before fib, qsort, queue and btree. Later we could add more. 

The benchmarks should of course measure the speed of the generated CakeML binary. The benchmarks file could also include other measures such as the length of the generated byte list. Later we can add more measures: number of executed machine instructions.

**Comment by xrchz** [comment]
This seems related to #40

**Comment by xrchz** [comment]
@tanyongkiam @myreen what exactly needs to be done here?

**Comment by xrchz** [comment]
I would say this depends on #331

**Comment by xrchz** [comment]
Can you make a Holmake target in the root directory that does this?
