### ISSUE TITLE
Switch translator to functional big-step semantics

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#112]
Currently the translator uses the relational big-step semantics. But I think we want to make the functional big-step semantics primary, and therefore having certificate theorems ultimately be defined in terms of it would be better.

**Comment by xrchz** [comment]
@myreen is there a specific route we could outline for getting this done?

**Comment by myreen** [comment]
The translator no longer uses the relational semantics. I'm closing this issue, since it is done.
