### ISSUE TITLE
Add monomorphic equality tests

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#113]
Monomorphic equality primitives allow for more efficient code for testing equality, because runtime tests for the types of objects are not required. Once such primitives are added, they can either be called directly by the programmer, or substituted for polymorphic equality after type inference.

See thread starting at https://lists.cakeml.org/private/dev/2016-May/001552.html.

**Comment by myreen** [comment]
I can't see type-restricted equality primitives being any faster in practice for ints, datatypes, or 64-bit words. Such primitives would only be marginally faster for bytes and ref/array pointers.

**Comment by xrchz** [comment]
We decided not to do this because it is not worth it. Could revisit again later if it seems we do a lot of comparisons on references or bytes and are losing speed there.
