### ISSUE TITLE
Change representation of bytes to avoid carry/borrow

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#120]
Currently, a byte `Word8 w` is represented as `Number (& (w2n w))` in `closLang` and thereby as `n2w (4 * (w2n w))` in `wordLang` and below. As a result, overflow on arithmetic operations (add and subtract) on bytes needs to be cleared out with shifts. ([example](https://github.com/CakeML/cakeml/blob/master/compiler/backend/bvp_to_wordScript.sml#L402.))

An alternative representation, mentioned [here](https://lists.cakeml.org/private/dev/2016-June/001611.html), would store the byte in the top bits of the machine word, so the overflow semantics matches the underlying machine semantics better and does not require shifts.

One complication with this: the `pat_to_clos` compiler might need to become aware of the target machine word size, to know by how much to multiply `w` for the bytecode value representation (i.e., `Number`).

**Comment by xrchz** [comment]
@myreen if this is no longer considered a good idea, close the issue?

**Comment by myreen** [comment]
@xrchz Indeed, this can be closed since the current representation is good. I want to note that #499 will rework most things regarding byte are words inside the compiler.
