### ISSUE TITLE
Remove unnecessary jumps in labLang

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#131]
Currently, compilation into `labLang` produces places where an unconditional jump jumps to the next instruction. Such jumps should be rewritten to `Skip` (which gets deleted by `lab_filter`) .

**Comment by xrchz** [comment]
I believe @cmr is working on this.

**Comment by xrchz** [comment]
@cmr no longer working on this; I might take over when I find some time.

**Comment by tanyongkiam** [comment]
This is superseded by #1080
