### ISSUE TITLE
Use app_list in bvl_to_bvi

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#133]
Currently, `stack_to_lab` defines an efficient `append` function that works better than naively calling `(++)`. (It operates on an `app_list` datatype designed to support efficient list-appending by delaying and combining calls to append.)

The same technology can and should be used by the `bvl_to_bvi` compiler (and possibly elsewhere). The `append` from `stack_to_lab` should be moved (probably to `miscTheory`), and then re-used in `bvl_to_bvi`.

**Comment by myreen** [comment]
I think `app_list` could be improved for `bvl_to_bvi`, since the current implementation (	1cb0988) produces a lot of `Append (List []) (Append (List []) ...)`.

How about adding `Nil` to the `app_list` datatype:

    app_list = List ('a list) | Append app_list app_list | Nil

and defining `SmartAppend` to avoid `List []`.

    SmartAppend l1 l2 = 
       if l1 = Nil then l1 else 
       if l2 = Nil then l2 else Append l1 l2

In `bvl_to_bvi`, use `SmartAppend` instead of `Append` and replace `List []` with `Nil` throughout.

I suggest adding a new constructor `Nil` because `SmartAppend` needs to be fast and matching on `list []` is a deeper pattern match that will be slower than an equality test with `Nil`.

I don't think it's worth using `SmartAppend` in `lab_to_target` because there `List []` is very rare.

**Comment by xrchz** [comment]
I tried this. I defined `SmartAppend` with `Define`'s pattern matching, but added your characterisation with the `if`s to the compset for evaluation. It seems to make no difference to the speed of producing the bootstrapping theorem, though. I wonder if I missed something simple. Or maybe that speed has nothing to do with append anyway.

**Comment by myreen** [comment]
If that still doesn't produce speed gains, then you could try narrowing down the problem by adding on/off switches to the various optimisations and trying which one makes it slow. Here are some notes:
 - one can already turn off `bvl_inline` with `c.inline_size_limit` set to `0`.
 - `bvl_handle` cannot be made optional
 - `bvl_const` and `bvi_let` can be made optional

**Comment by xrchz** [comment]
I think the appends in `compile_single` and `compile_list` could also be problematic. I had to call `append` in `compile_single` because it wants to do `MAP`, but that means those lists get traversed twice (once for the `MAP`, once when appending in `compile_list`).

**Comment by xrchz** [comment]
It seems like this might be becoming another bottleneck in the bootstrap. @myreen, what do you think about `compile_single` as mentioned in the comment above? I haven't yet investigated exactly where the slowdown is, though (apart from in bvl-to-bvi).

**Comment by myreen** [comment]
I think you are right, both `compile_single` and `compile_list` have bad appends. Could this be resolved by moving `append` out to `compile_prog`, i.e. leaving things in the `app_list` type for longer so that the appends are all computed using `append` once at the top-level only?

**Comment by xrchz** [comment]
@myreen yes, I think only doing `append` once at the top level would be a good idea. Can you see how to change the definitions to achieve that? Can we avoid having to add a `map` constructor to the `app_list` type?

**Comment by myreen** [comment]
You can avoid the `MAP` by just pushing it into `compile_exps`. What I mean is: the `MAP` is applied to `aux` but `aux` is produced by `compile_exps` one element at a time, each time an element is produced just apply the function the `MAP` would apply afterwards.

**Comment by xrchz** [comment]
I think this issue itself is now done, but evaluating `bvl_to_bvi` is still too slow. Preliminary investigation suggests it may be due to `bvl_const` or `bvl_handle`. There is one _giant_ program (the main expression) to evaluate at this point, and then about 3000 other little ones (the stubs and function bodies) - I think only the giant one is a problem, which suggests non-linear complexity in one of these passes.

**Comment by xrchz** [comment]
I can confirm that the slowdown is due to `bvl_handle` on the giant expression (at least - there may be more slow parts after that phase), and not `bvl_const`.
