### ISSUE TITLE
Make CF and translator able to use each other's specs

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#134]
The CF framework and translator both produce proved theorems about CakeML values.

They should be able to use each other's results:
1. if the translator has a certificate thm for `foo`, then CF should be able to use this in CF proofs that include `foo` 
2. if the CF tools have verified that `foo` has _pure behaviour_, then the translator should be able to use it

What is _pure behaviour_? If the function spec does not assume state nor alter externally visible state.

**Comment by myreen** [comment]
I think **translator → CF** should be easy-ish.

The challenge with **CF → translator** is that the translator requires code to start from an empty state and result in an empty state. The requirement that the resulting state must be empty ought to be relaxed somehow. It's not clear to me how that could/should be done.

It would be cool to be able to verify a memoization function in CF and use it in the translator as if it is pure.

**Comment by xrchz** [comment]
I guess the problem in #99 depends on the easy half of this issue.

**Comment by Armael** [comment]
Yes, #99 will be solved by implementing the *translator -> CF* part. Working on it now.

**Comment by xrchz** [comment]
I think this is done. (In particular the series of commits from ff94741 to 389bc2c seem to have done it.)
