### ISSUE TITLE
Optimise GetGlobal for Number constants in clos_known

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#138]
The `clos_known` optimisation tracks where values flow and can find that a `GetGlobal` will always return a specific number. In these cases it would make sense for `clos_known` to turn the `GetGlobal` into a `Const ...`. Such a change would allow BVL's constant folding routine, `bvl_const`, to make the code better.

**Comment by mn200** [comment]
Cool idea.  I'll definitely take a look.

**Comment by mn200** [comment]
Hmm. This is not quite so simple.  Calls to `SetGlobal` pass closures, not numbers, and similarly, the expected returns from `GetGlobal` calls are closure values. The `known` pass would have to record the actual `Fn` expression in its approximation map, and then substitute that expression for the `GetGlobal`. (And it would have to make sure not to recurse into that expression :-) Would that be worth doing?

**Comment by myreen** [comment]
I'm a bit confused now. It's true that known is mostly interested in where closure values flow. However, it also tracks where integers flow.

How does the following example assign closures to globals?

    val c = 4;
    val z = c + 5;

I would have thought that the example above would become:

    SetGlobal 0 4 ;
    SetGlobal 1 (get global 0 + 5)

And would have thought that known knows that `GetGlobal 0` always returns `4`. Thus known could optimise the second line above to:

    SetGlobal (4 + 5)

Later in BVL, `4 + 5` gets collapsed to `9`.

In terms of code change to the compiler, this would be a very small change to the op case only: if the op is a `GetGlobal` and the returned approximation is some `Int`, then replace the op with `Op (Const ...) []`.

This is not exactly a major optimisation, but I hope it would also be easy to add.

**Comment by mn200** [comment]
Ah!  I hadn't thought about just the Int values.

**Comment by myreen** [comment]
By the way, as an extension: would it be difficult to make the approximations also track tags of conses/blocks, i.e. `Block tag ...`? A similar `GetGlobal` optimisation could be done for empty conses (such as `true`, `false` and `[]`). I would imagine that it would be helpful in removing dead code in case someone writes:

    val debug = false
    ...
    fun complicated_function ... = ... (if debug then print-lots-of-stuff else ()) ...

Currently the approximation tracks blocks/conses as `Tuple`. Maybe it would just be a matter of adding the `tag` number to the `Tuple` approximation. The optimisation could always replace a `GetGlobal` that loads a `Tuple tag []` with `Op (Cons tag) []`, for any value of `tag`.
