### ISSUE TITLE
Automatically introducing tail-recursion in bvl-to-bvi

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#140]
Tail-recursive functions compile to better code than non-tail-recursive functions. Can we make functions more tail-recursive automatically in a compiler? Yes!

_Example 1:_ length of a list — reason for opt: addition is associative

```
fun length [] = 0
  | length (x::xs) = length xs + 1

 ||
 ||
\||/
 \/

fun length' [] acc = acc
  | length' (x::xs) acc = length' xs (acc + 1)

fun length xs = length' xs 0
```

_Example 2:_ factorial — reason for opt: multiplication is associative

```
fun fac n = if n <= 0 then 1 else fac (n-1) * n

 ||
 ||
\||/
 \/

fun fac' n acc = if n <= 0 then acc else fac (n-1) (acc * n)

fun fac n = fac' n 1
```

_Example 3:_ quick sort — reason for opt: list append is associative

```
fun qsort xs = let ... in qsort xs1 ++ [x] ++ qsort xs2 end

 ||
 ||
\||/
 \/

fun qsort' xs acc = let ... in qsort' xs1 ([x] ++ qsort' xs2 acc) end

fun qsort xs = qsort' xs [] 
```

The transformations would fit well in the bvl-to-bvi phase of the CakeML compiler since this phase allows allocating new code-table entries and allows adding new ticks to the clock.

This is not an easy project but could be a nice topic for a Masters thesis. Contact me if you are interested and have relevant background.

**Comment by xrchz** [comment]
I believe this can be closed now that #294 is merged.
