### ISSUE TITLE
Prove and save EqualityType lemmas in compiler translation

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#146]
Currently, the translation in `compiler/bootstrap/translation` generates `EqualityType` assumptions. These should be proved and registered with `store_eq_thm` as early as possible, to avoid unnecessary propagation. The proofs can likely be found in `version1`.

**Comment by tanyongkiam** [comment]
I think this comment is related (it occurs when translating the wordLang prog datatype): https://github.com/CakeML/cakeml/blob/master/compiler/bootstrap/translation/to_word64ProgScript.sml#L120

**Comment by thtuerk** [comment]
Sorry, I caused trouble with the changes to lifting that made 70e4aaf necessary. But I hope the new version is much better than the old one.

**Comment by IlmariReissumies** [comment]
No worries, I'm glad it's being worked on! In particular I like that the 
new version seems to yield less FST,SND-clutter in the goals.
