### ISSUE TITLE
Make regression test timeout more informative

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#148]
Currently `developers/build-email.sh` will, in the case of a timeout, only print the directories that were built successfully so far.

It would be helpful to also print the tail of the `regression.log` in the directory that timed out, to better diagnose where the timeout occurs.

In the current setup, this might require reading `developers/build-sequence` to see what the current directory being tested is; building better regression infrastructure is another option.

**Comment by ajaysusarla** [comment]
@xrchz are there any requirements (somewhere in the wiki perhaps, although  a search in the wiki didn't show anythin) for what the regression test infrastructure needs to have?
The other questions I have are:
* How long does the regression run for(on a successful run)? (I see there is a timeout for `12h` in the script, assuming it is much lesser than that.
* I also notice that there is a reference to `selftest.exe` in the `build-travis.sh` and `regression-test.sh`, but I don't see a rule to generate it, is there something that needs to be run to get that?

**Comment by xrchz** [comment]
There are no written requirements that I know of. What do you mean?

I can answer the other questions though:
- A successful run currently probably takes more than 12 hours. I haven't seen a successful run in a long time. The problem is the `compiler/bootstrap` directory, which currently takes several hours. Before we added the bootstrap, a full run would be done in 4-6 hours I'd say.
- If a `selftest.exe` gets generated by `Holmake` in a directory, the regression test will try to run it; but if it doesn't get generated that's no problem. (Thus it is up to each directory's `Holmakefile` to specify how to build `selftest.exe` if one is appropriate. I don't think many directories use it, maybe none.)

**Comment by ajaysusarla** [comment]
@xrchz thanks much for the answers.
My earlier question regarding requirements was to check if there were upper-bounds for timeouts and such, for me to work against.
I'll start working on this issue. Thanks again!
