### ISSUE TITLE
Translator fails on partially applied functions with side conditions

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#15]
Suppose function `foo` takes two arguments `x` and `y`, and there is a side condition `foo_side x y = ...`.

Then any translation that doesn't fully apply `foo` fails, e.g. `MAP (foo x) ys`.

**Comment by xrchz** [comment]
This is probably related to (and maybe the same as) #9.

**Comment by xrchz** [comment]
Same as #9 so closing this one.
