### ISSUE TITLE
Remove duplicate shift type

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#156]
As pointed out by @mn200:
There are two identical types called shift (with constructors `Asr`, `Lsl` and `Lsr`).
One is in `semantics/ast`, and the other is in `asm`.

I suggest we have one copy of this type in `misc` instead.

**Comment by xrchz** [comment]
Is this done? What more is required after 0690700?

**Comment by myreen** [comment]
Yes, it's done.
