### ISSUE TITLE
Adding set_grammar_ancestry calls into lem-generated scripts

### ISSUE THREAD

**Issue by mn200** [CakeML/cakeml#157]
I'd like to have `semantics/astScript.sml` include a call to something like

    set_grammar_ancestry ["string", "word" "integer"]

so that its grammar doesn't pick up a whole lot of extra cruft (*e.g.*, FFI stuff). 

I don't know how `lem` might be persuaded to do this.

**Comment by xrchz** [comment]
One (awful) option: `sed` script or equivalent...

Another thing to check: `lem` seems to have some target-specific declaration stuff that maybe would allow inserting new strings? https://www.cl.cam.ac.uk/~pes20/lem/built-doc/lem-manual.html#target-representation-declarations - I don't know what `compile_message` is there, but maybe that?

Ask the `lem` [mailing list](mailto:cl-lem-dev@lists.cl.cam.ac.uk) or [bug tracker](https://bitbucket.org/Peter_Sewell/lem/issues/)...

**Comment by mn200** [comment]
See 2de67e2e3d for an SML implementation of the awful option.
