### ISSUE TITLE
astPP needs to parenthesise nested case expressions

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#16]
nested case expressions are often ambiguous to parse; the pretty-printer should include enough parentheses for disambiguous parsing.

**Comment by tanyongkiam** [comment]
This is partially fixed on the reg_alloc branch. However, I think there might be the same problem with letrecs (not completely sure).

**Comment by xrchz** [comment]
Although I'm not completely certain, I think the case expression problem is now fixed (now that reg_alloc has been merged into master). (No idea about letrec.)
