### ISSUE TITLE
Type error: unbound variable for targets {isabelle}: nat_set_to_set

### ISSUE THREAD

**Issue by larsrh** [CakeML/cakeml#17]
Using a recent (71e8c68) version of Lem, I'm getting the above error:

```bash
$ ../../lem/lem -isa -lib ../../lem/library *.lem
File "lib.lem", line 48, character 58 to line 48, character 71
  Type error: unbound variable for targets {isabelle}: nat_set_to_set
```

I'm unsure how to debug this, but it looks like a problem with CakeML, because `-hol` works fine on my machine.

**Comment by xrchz** [comment]
The problem is that ```nat_set_to_set```, specified in CakeML's ```semantics/lib.lem```, is only given a target representation for HOL4, not for Isabelle/HOL. The quickest solution would be to declare a suitable target for Isabelle/HOL (you can do that in ```lib.lem``` itself). The right way would be to, if it exists, use a function that is already defined in Lem's library (and has target representations for all of Lem's supported targets).

**Comment by xrchz** [comment]
On closer inspection, it seems unlikely that there will be a good target in Isabelle, since this is using HOL4's new `sptree` type. However, you could just use whatever Isabelle's default representation of finite sets is.

**Comment by larsrh** [comment]
I'm looking at these declarations now:

```
type nat_set
declare hol target_rep type nat_set = `spt` unit
val nat_set_empty : nat_set
val nat_set_insert : nat_set -> nat -> nat_set
val nat_set_to_set : nat_set -> set nat
```

Can I just represent `nat_set` as set of `nat`s? In that case, `nat_set_to_set` would be just identity. (Of course, regular Isabelle sets can be infinite.)

**Comment by xrchz** [comment]
> Can I just represent ```nat_set``` as set of ```nat```s?

Yes.

(Depending on what you're using the generated theory for. We use ```sptree```s in the compiler because they provide an implementation of sets with good performance both inside the logic and in our generated code.)
