### ISSUE TITLE
Add word literals to closLang, BVL, BVI, dataLang

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#170]
Currently, if a user writes a word literal `w`, this gets turned into `Op WordFromInt (Op Const (w2n w))` which produces code that creates a bignum which could easily be avoided.

**Comment by talsewell** [comment]
I haven't thought this through yet, but wouldn't it be simpler to let the conversion happen but make sure it gets evaluated/optimised back to a word literal in WordLang?

**Comment by xrchz** [comment]
An advantage of optimising such expressions is that we wouldn't just be optimising source-level word literals.

**Comment by myreen** [comment]
@talsewell when the expression `Op WordFromInt (Op Const (w2n w))` passes through the `data_to_word` compiler phase, the `Op Const (w2n w)` part generates an allocation(*) in WordLang that cannot be removed as a WordLang-only optimisation, because internal WordLang compiler passes do not have access to the (complicated) state relations between DataLang and WordLang.

(*) Note that allocation code is only generated if `w2n w` does not fit within a small integer (62 bits on 64-bit architectures).

It might be sufficient to introduce a word literal only in DataLang and have the `data_simp` pass or similar compiler phase turn `Op WordFromInt (Op Const k)` into the new word-literal operation.

**Comment by myreen** [comment]
This issue is related to #499.

**Comment by talsewell** [comment]
@myreen : OK, that clarifies a lot.

I think we need to talk about the (*) bit though. If allocation code is only generated for integers above 30/62 bits, is this really an issue? How many source files contain 10-digit numerals, and do we care about the resulting performance?

**Comment by myreen** [comment]
@talsewell you are right that this is a niche improvement to the compiler that might not result in any noticeable performance boost.

**Comment by myreen** [comment]
@talsewell by the way, #376 is a proposed optimisation that is much more likely to produce a noticeable performance boost.

**Comment by talsewell** [comment]
Well, we now think we know what the compiler will do, and think that it's probably not worth changing.

I am going to try to confirm that knowledge empirically, but I'm not sure how difficult that will be.

**Comment by tanyongkiam** [comment]
This is done https://github.com/CakeML/cakeml/blob/8c68847abd8fee8b25a2e9fbacd3a2089f6e986d/compiler/backend/flat_to_closScript.sml#L45
