### ISSUE TITLE
addancs adds duplicate calls?

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#177]
I keep finding `semantics/astScript.sml` being modified, when I rebuild cakeml, with a duplicate line calling `set_grammar_ancestry`. Is there something in the `Holmakefile` or `addancs` script that would lead to this duplication on rebuild? (I haven't looked into it much yet, but wondering if someone else might know better quicker)

**Comment by mn200** [comment]
I guess this is because you don't have lem installed, and the Holmakefile incorrectly calls `addancs` even when it has only `touch`-ed `astScript.sml`.  

I will commit what I think is the right fix to the logic in the Holmakefile.
