### ISSUE TITLE
Translator's update_precondition fails when there are custom ML names

### ISSUE THREAD

**Issue by ConnorCashman** [CakeML/cakeml#179]
`update_precondition` evidently calls `save_thm` which fails if there are ML names like "~" around which cannot be the names of theorems. The translator needs to be more careful with names.

**Comment by xrchz** [comment]
@ConnorCashman can you check whether calling `update_precondition` still fails if used after "~" has been added to the ML prog lib state? If it now succeeds, we can close this issue.

**Comment by xrchz** [comment]
Connor suggested this works now.
