### ISSUE TITLE
ILs should have more primitive ops

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#18]
Currently only < is a primitive, which leads to awkward inefficient translation out of patLang. There's no reason any more not to support more primitive operations directly.

**Comment by xrchz** [comment]
@myreen: which operations exactly can be added to BVL?

**Comment by myreen** [comment]
Which operations are difficult to translate from patLang? I know <= should
be added to BVL.

**Comment by xrchz** [comment]
Nothing is difficult to translate from patLang. The problem is that the translations are not as efficient as they could be if there were dedicated operations in the target language. Hence I think it's better to just add operations you know will be efficient. Greater-than?

**Comment by SOwens** [comment]
Why not just keep all of the operations?

-Scott

**Comment by xrchz** [comment]
It's not a matter of keeping them since the BVL ops are defined from scratch rather than inheriting anything from above. I want to make sure any op added to BVL can be compiled easily further down.

**Comment by myreen** [comment]
It would be good to have a list of all operations that do not have an
immediate equivalent in BVL. Add greater than to BVL. -- Magnus

**Comment by xrchz** [comment]
The way to get such a list is to look at the definition of `pComp` in `pat_to_closScript.sml`, and decide which operations' translations are not "immediate" enough. It's possible that `Gt` and `Geq` are the only ones left, but they are not the only operations that introduce (sometimes multiple) `Let`s.

**Comment by xrchz** [comment]
Is this done now?

**Comment by myreen** [comment]
Just had a look. The pat-to-clos compiler looks good to me.
