### ISSUE TITLE
const_fp compilation phase uses functions from asmSem

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#184]
In particular, `const_fp_loop` seems to use `asmSem$word_cmp`. The compiler should not be using the semantics. The right thing to do in this case is probably to move `word_cmp` into `asmTheory`.

**Comment by AndreasLoow** [comment]
Hopefully fixed in the const_fp branch now. Only word_cmp was moved. Will close this when that branch is merged.

**Comment by xrchz** [comment]
I think this is done.
