### ISSUE TITLE
update_precondition breaks CF in catTheory

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#193]
Uncommenting the `update_precondition` here https://github.com/CakeML/cakeml/blob/master/compiler/bootstrap/io/catScript.sml#L184 breaks the rest of the file. This should not happen.

**Comment by Armael** [comment]
I suspect this is an issue with the translator? From the CF side, what I can observe is that, after uncommenting the `update_precondition` line,  translator-produced theorems mention intermediate definitions that used to be cleaned up by the translator. Therefore `xsimpl` does less work and the proofs break.

For example, `word8_from_int_v_thm` becomes `|- (NUM --> WORD) Word8_fromInt word8_fromint_v`, where `|- Word8_fromInt = n2w` (`Word8_fromInt_def`). Previously, `word8_from_int_v_thm` was directly `|- (NUM --> WORD) n2w word8_fromint_v`.
