### ISSUE TITLE
Replace EVAL_TAC in ioProgLib

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#200]
> proving the final theorem takes extremely long
> because it must calculate no_dup_top_types and no_dup_mods for
> entire_program by EVAL_TAC

See https://lists.cakeml.org/pipermail/developers/2016-November/000041.html

These checks ought to be done by custom conversions at least. And maybe the translator or `ml_progLib` could store more information to make them easy to compute?

**Comment by SOwens** [comment]
After the env-refactor branch is merged, we could think about changing the semantics to support duplicate definitions.

**Comment by IlmariReissumies** [comment]
I'm looking into writing custom conversions for these
