### ISSUE TITLE
Translator can't distinguish functions in different files/modules

### ISSUE THREAD

**Issue by ConnorCashman** [CakeML/cakeml#206]
Functions with the same name in different modules e.g. mllist$foldli and mlvector$foldli aren't distinguished by the translator - it translates the second function to be translated as foldli_1. This also affects the names of the side conditions.

**Comment by tanyongkiam** [comment]
You can set use_long_names := true

**Comment by xrchz** [comment]
This can also be worked around using the `next_ml_names` reference. I don't think there is any clear desired alternative functionality here, so I'm closing it.
