### ISSUE TITLE
Parser doesn't handle op keyword

### ISSUE THREAD

**Issue by mn200** [CakeML/cakeml#21]
Our handling of infixes is very restricted, but it would still be nice to be able to write

    fun hof f x = f(x,x);
    hof op+ 3;

This fails at the moment: the grammar doesn't have any rules at all including the `OpT` token (which the lexer produces).

**Comment by xrchz** [comment]
Is this still open as of a9905da52cba70d1611768e57cea4660606975a9?

**Comment by mn200** [comment]
Strictly, no.  The parser does indeed translate things involving `op` as *per* the grammar in `gramScript`.  The way things are typed after being parsed is non-SMLish as we discussed on the mailing list.
