### ISSUE TITLE
Translator fails on sum type datastructures with recursion

### ISSUE THREAD

**Issue by dustblaze** [CakeML/cakeml#212]
For example
``val _ = Datatype`
  sumType = A (sumType + num)
           | B num
`
``

``val func_def = Define`
  func (A _) = T
`
``

``val _ = translate func_def``

will result in failure. An error message appears when attempting to translate the function twice stating that it 

> Cannot translate term:  sumType_CASE

**Comment by xrchz** [comment]
I also had trouble translating that type. My current suspicion is that it might require doing the "TODO" mentioned on this line https://github.com/CakeML/cakeml/blob/master/translator/ml_translatorLib.sml#L959

**Comment by xrchz** [comment]
Indeed, the translator currently uses a type's "size" theorem to determine whether it's mutually recursive. (See https://github.com/CakeML/cakeml/blob/master/translator/ml_translatorLib.sml#L959.) So in your case, it (incorrectly, I am guessing) thinks that `sumType` and `+` are in mutual recursion. Then the "TODO" above applies - the `eq_lemmas` computation doesn't yet support mutual recursion.

@myreen might have thoughts on the appropriate way to move forward with this.

**Comment by myreen** [comment]
Last time I looked at the automatic proofs of eq_lemmas, the code was not
particularly general or well tested. Feel free to improve the code or even
rewrite it completely.

**Comment by xrchz** [comment]
@tanyongkiam I made a pull request, and regression tests are looking good. Anything to add, or ready to merge?

**Comment by tanyongkiam** [comment]
Yes, it seems like the way I made the translator report that it failed to prove an EqualityType lemma was incorrect.

However, that shouldn't affect this issue and can be fixed separately later, so let's just merge it now.
