### ISSUE TITLE
Move, clean up and improve ioProgLib

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#225]
Several applicants will use only I/O of the form: 
 1. read all input from stdin
 2. read all commandline arguments
 3. perform some translator generated function
 4. print result to stdout
 5. exit

Currently, `ioProgLib` helps build programs that have the I/O behaviour above. However, the way `ioProgLib` is placed in the directory `compiler/bootstrap/io` suggests the file is specific to the compiler.

This issue is about:
 - Moving `ioProgLib` to the `basis` directory
 - Making `ioProgLib` read commandline arguments and pass to compile functions
 - Moving `main` from ioProgLib to ioProgTheory with compile as a higher-order argument
 - Minimizing the amount of code in `ioProgLib`

**Comment by xrchz** [comment]
@ConnorCashman is working on parts of this on the basis branch.

**Comment by xrchz** [comment]
So, on the basis branch, I think this is almost all done. What is missing is defining and verifying a higher-order `main` function. (echo, hello, and the bootstrapped compiler all define their own `main` currently.)

cat and grep won't fit into this framework as it is because they also require the filesystem FFI (which is not part of `basis_ffi`), but Connor I think wrote comments indicating how his approach can easily be adapted to a different FFI oracle.

**Comment by xrchz** [comment]
@myreen is making `main` higher-order necessary for this issue? Given #228, the `main` function might be returning an `mlstring app_list`, or sometimes it might be an `mlstring` or sometimes a `char list` or ... Do we want to standardise on one of these and fix it into the `main` function? The exact form of the specs also differs slightly between examples. I'm starting to prefer the current approach where the user proves their own `main_spec` but can hand it off to `call_main_thm` to get the final `semantics_entire_program` theorem.

**Comment by myreen** [comment]
It sounds as the current solution is more flexible. I hope it's easy to use. I'm fine with `main` not taking a function as an argument.

**Comment by xrchz** [comment]
Well, you can see how it's used with some examples:
https://github.com/CakeML/cakeml/blob/basis/characteristic/examples/echoProgScript.sml#L46
https://github.com/CakeML/cakeml/blob/basis/compiler/bootstrap/translation/compiler_x64ProgScript.sml#L174

When the basis branch is merged I'd say this can be closed.

**Comment by xrchz** [comment]
The basis branch lives on with some further work in this vein, but I'd say as of about 78aab6d4 this is done.
