### ISSUE TITLE
patterns in function definitions

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#23]
`fun` and `fn` currently only allow variables as formal parameters. For users writing CakeML code, it would be nice to support full-blown patterns (as in SML). There is a question of whether these should be handled solely by the parser (i.e. parsed to a match expression in the body) or should affect the AST. I think keeping it in the parser is better. I think the parser already expands multiple variables to nested lambdas.

**Comment by mn200** [comment]
The latter was done in b10d89d8b.  

If it's clear what the translation has to be, it'd probably be easy enough to put it into `cmlPtreeConversion`.

**Comment by mn200** [comment]
If I have to translate 

    fun f (x,y) = x + 2 * y

into 

    fun f p = case p of (x,y) => x + 2 * y

then I have to invent names for fresh variables.

If I was able to translate to `fn pat => body` that would be easier...

Note that the SML definition suggests translating `case e of patexps` into `(fn patexps) e` which is nice again for not needing fresh name generation.

So, any chance of having `fn patexps` as a suitable primitive target when removing syntactic sugar?  And then I suppose things like `fun f pat11 pat12 = e1 | f pat21 pat22 = e2` could be translated into 

    fn pat11 => (fn pat12 => e1) | fn pat21 => (fn pat22 => e2)

(a use for `ZIP`).

**Comment by xrchz** [comment]
Possibly the right thing is to replace the `Fun` AST form with one that takes `patexps`. But would we changed `Closure` too? If not, I think names need to be generated somewhere. Either way, we probably want to discuss options further (maybe on the Dev list) and hold off on changes until the `new_compiler` branch is more stable (or merged back).

**Comment by SOwens** [comment]
In general, I think we should consider working toward removing syntactic sugar rather than introducing it. Especially non-trivial syntactic sugar that involves fresh names.

The parse-tree to AST conversion (which contains the implementation of de-sugaring) is one of the most difficult to read parts of the semantics. It (along with the much simpler lexer) is also the least validated: everything else has a provably equivalent implementation version. So while it�s more work to add to the source AST, I think it gives an easier to understand and more robust semantics to do so. Then the redundant features can be removed in the compilation to the first intermediate language.

-Scott

**Comment by xrchz** [comment]
I agree with Scott that we should aim to make parse-tree-to-AST conversion as simple as possible. (To achieve that either make the concrete syntax less user-friendly or make the AST more complex; we should aim for more user-friendly concrete syntax.)

**Comment by myreen** [comment]
I would prefer to keep it simple and just allow matching over tuples in Fn in the source semantics.

The following are in my opinion fine:

fn () => ...
fn x => ...
fn (x,y) => ...

But I'm not too happy with other matches, e.g. the following.

fn NONE => ...
fn INL x => ...

See also issue #24.

**Comment by xrchz** [comment]
What do you mean by "source semantics"? The AST or the concrete syntax? I am against making the concrete syntax less usable in principle, though I acknowledge that it may not be a high priority.

**Comment by myreen** [comment]
I meant that we should allow tuple patterns both in the concrete syntax and
the abstract syntax.

**Comment by xrchz** [comment]
I agree, but I also think we should allow patterns that use other constructors (in both).

**Comment by myreen** [comment]
... I've changed my mind. I now agree that general patterns are desirable. I was convinced by the following example:

    datatype 'a state = State of 'a;
    ... fn State s => ...

My view on the main question: 

- In the long-term, patterns should only be added to Fn in the concrete syntax if they are also added to the AST. 
- However, in the short-term I'd be happy with a hack, for example: when inventing the name, just pick a name that cannot be parsed, e.g. the empty string (denoted by `ε`). With this `fn (x,y) => ...` turns into `fn ε => case ε of (x,y) => ...`

**Comment by mn200** [comment]
Cool.  If you never need to invent multiple such names (and I guess you don't), then this makes for a fairly easy hack.  I will try to finish handling `op`, and then work on this.
