### ISSUE TITLE
Source-to-source transformations and code refactoring

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#24]
Currently we have no source-to-source transformations. I wonder if we should consider having such (and make issue #23 such a transformation). Having infrastructure for doing source-to-source transformations could lead to nice verified refactoring tools.

**Comment by mn200** [comment]
What "source" do you want to transform?  Source as character sequence, token-sequence, parse-tree, or AST?  If later phases are transformed, do you want to print back to character sequences as the final output?

**Comment by myreen** [comment]
I was thinking in terms of the AST and, to start with, mostly refactorings that the compiler could do as a first step. The most interesting such would be lambda lifting. Why at the source level? My answer: because we can (in principle) access type information at this level, and any infrastructure built around these transformations could be used for other AST-level work.

Any transformation of the source syntax would at least go via the AST... We could prove some form of print-then-parse identity (but that sounds like a lot of tedious work!). A more pragmatic approach could be to evaluate `parse (print ast) = ast` for the particular `ast` that we are about to print.

**Comment by mn200** [comment]
I totally agree about not wanting to bother with printing (it was silly question on my part).

Would you know that lambda-lifting was a good idea at the AST level?  My impression is that this sort of thing would be done later.

**Comment by myreen** [comment]
It would make sense to do lambda lifting at closLang (the last language with closures), but I have the impression that verified lambda lifting requires access to types (closLang is untyped) and a lot of proof infrastructure (that should ideally be reused for other transformations either at the level of source or closLang).

**Comment by SOwens** [comment]
Why do you think that verified lambda lifting will need access to types? Scheme compilers do lambda lifting, and I don�t believe that they inherently unverifiable.

-Scott

**Comment by myreen** [comment]
The reason I thought we needed types for lambda lifting is that I thought the (very vague) plan was to do the verification proof in terms of a type-based notion of contextual equivalence (which would be nice to have for the source). However, I believe you are right. We might not strictly speaking need types or a general notion of contextual equivalence for lambda lifting.

**Comment by SOwens** [comment]
A type-based contextual equivalence for the source would be good to have. But I think that either a typed or untyped contextual equivalence thing should suffice for lambda lifting.

-Scott

**Comment by xrchz** [comment]
This issue seems too vague. What would it take to get it closed? Can we move the discussion to the wiki or mailing list and close the issue?

**Comment by xrchz** [comment]
@myreen: please reply to the comment above
