### ISSUE TITLE
Parser can't apply constructors correctly

### ISSUE THREAD

**Issue by mn200** [CakeML/cakeml#25]
The parser (all the way up to `cmlPtreeConversion`) can't correctly apply constructors to arguments because it doesn't have information about what the constructor arities are.  For example, `SOME(x,y)` should translate to 

```
Con (Short "SOME") [Con NONE [x,y]]
```

but `x::y` has to translate to 

```
Con (Short "::") [x,y]
```

The behaviour at the moment is to treat `SOME` applied to a pair like the second case, and to incorrectly generate `Con (Short "SOME") [x,y]`, which leads to a type error.

**Comment by xrchz** [comment]
I think it's not too hard to give such information to the parser (the compiler knows it somewhere, at least in the type inferencer's state). Is it easy to modify the parser to use it?

**Comment by SOwens** [comment]
It�s tricky.

If I say 

datatype t = SOME of int * int * int
val x = SOME (1,2,3)

without the semicolon, then doesn�t the parser do the whole thing in 1 go?

-Scott

**Comment by xrchz** [comment]
I don't think so. We require each top-level declaration to be processed separately. There should be a semicolon before `val`.

**Comment by SOwens** [comment]
Ok. Then it should should work ok since we don�t have local datatype definitions. But it does further complication the parse tree to AST phase, which is the part that needs simplification�

-Scott

**Comment by mn200** [comment]
If we do require extra semi-colons, it's through no requirement of mine.  The grammar has no problem with omitted semicolons in positions such as the above.  

Of course, Scott is right that handling this bug does make things more complicated.  I'd prefer to have the phase that resolves applications to come after `cmlPtreeConversion`.  Handling each declaration and fixing constructor applications should then be a relatively straightforward state monad.

**Comment by xrchz** [comment]
I believe the semicolons requirement comes from parsing against `nREPLTop` and using `split_top_level_semi` here https://github.com/CakeML/cakeml/blob/master/semantics/replScript.sml#L75

**Comment by SOwens** [comment]
We might have to add an elaborator, or change the type system to compute a new term (effectively combining elaboration with type checking). Both are more work than just hacking the PtreeConversion, but I prefer them.

-Scott

**Comment by mn200** [comment]
I don't understand why we don't parse against the `REPLPhrase` constructor that commit 2cb75c39b0 removed.  This would return a list of declarations followed by an optional expression and still behaves nicely with respect to the top-level semi.

**Comment by xrchz** [comment]
It's possible I was confused about something when I made that commit. It's also possible that using `REPLPhrase` makes something under `repl` or `repl/proofs` harder. I'm open to changing the semantics to parse against `REPLPhrase` again (although probably won't work on it myself for a while).

**Comment by xrchz** [comment]
Is this still relevant given the recent work on Haskell-style datatype declarations?

**Comment by mn200** [comment]
Strictly speaking, I think we should leave it open (and maybe assign to @SOwens) because we can no longer write

````
datatype 'a tree = Lf | Nd of ('a tree * 'a * 'a tree)
val tree1 = Nd(Lf, 1, Lf)
````

There's a workaround (write `Nd Lf 1 Lf`) so we're in a better place than we were, but I think the intention was to support the old SML style as well as the curried Haskell style.  Moreover, my understanding is that the plan is to have the handling of this be later than `cmlPtreeConversion`.

**Comment by xrchz** [comment]
@SOwens Any progress?

**Comment by xrchz** [comment]
Can we close this by giving up on supporting SML-style constructor applications? (I personally haven't been keeping track of what this even means, since I almost never use CakeML concrete syntax.) Suggestion to give up on this support came from @myreen.

**Comment by myreen** [comment]
I agree with @xrchz. I have previously argued for attempting to support both legacy SML style and our preferred Haskell-style constructor syntax in parallel. In light of moves such as #570 to improve on SML, I now think we should stop trying to support SML style constructor syntax.

**Comment by mn200** [comment]
Everyone's agreed on this I think.
