### ISSUE TITLE
Possible to have "brew install cakeml" ?

### ISSUE THREAD

**Issue by abhi18av** [CakeML/cakeml#252]
Hi CakeML team!!

This project is really interesting and I wanted to try out this implementation in the Programming Languages course on Coursera but I keep running into build errors while installing it. 

Could you please fix up something like `brew install cakeml` to make the installation process smoother?

**Comment by xrchz** [comment]
What errors are you running into?

**Comment by xrchz** [comment]
closing this for now - reopen with more info if necessary.
