### ISSUE TITLE
Introduce FFI into wordLang

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#26]

**Comment by xrchz** [comment]
I guess after 4a04975ca796766443b223fdd803d79bb40c3538, we just need to update the compiler proofs to close this?

**Comment by tanyongkiam** [comment]
Yes, specifically, I need to:
1) Properly setup the calling conventions for FFI calls in the register allocator/SSA phase.
Conventions are: every var in the cutset is a stack var and the ptr,len arguments to FFI are 2,4 respectively
2) Update the liveness analysis (should be similar to Alloc)
3) Add handling for FFI in instruction selector (should be identity)
4) Fix the proofs related to 1-3) and also remove the previous cheats related to FFIError in the semantics

**Comment by tanyongkiam** [comment]
Closed by series of commits: 835e273 8068286 4a04975
