### ISSUE TITLE
CakeML should return non-zero on error

### ISSUE THREAD

**Issue by michael-roe** [CakeML/cakeml#260]
On Unix-influenced operating systems, it is usual for programs to return a non-zero status on error. For example, compilers will return non-zero if an error was encountered during compilation.

At the moment, the bootstrapped CakeML compiler seems to return 0 whether or not compilation succeeded; it should return non-zero on failure.

**Comment by xrchz** [comment]
Agreed. Probably @myreen knows best how to achieve this.

**Comment by myreen** [comment]
One should probably have an FFI function called `exit_with_code`. The implementation on the C side is to call `exit` with the first element of the byte array that's given as argument. The semantics is that this is a non-returning FFI call, i.e. `Oracle_diverge `.

**Comment by michaelsproul** [comment]
I'm going to try tackling this, as a way of becoming familiar with the FFI internals

**Comment by michaelsproul** [comment]
Hi @myreen @xrchz! I tried to make some progress on this issue, but I'm stuck on the characteristic formula proofs. You can see my work-in-progress code here: https://github.com/CakeML/cakeml/compare/master...michaelsproul:issue260

It's not clear to me how divergence should work in a characteristic formula proof... both `POSTv` and `POSTe` seem wrong for a function that never returns. The first proof to break when I changed the definitions was `main_spec` in `compiler64ProgScript.sml`. From there I back-tracked to trying to prove something simple about the `exit_with_code` function itself.

I'd also like to understand exactly how the oracle (which I modified) interacts with the characteristic formulae, as I haven't been able to work that out (i.e. I haven't seen my change to the oracle effect anything). Pretty much any tips/explanations/pointers would be greatly appreciated! 🙂 

Thanks!

**Comment by michaelsproul** [comment]
For now my code has the `exit_with_code` function in the `Comandline` module, but I plan to move it to `Runtime`

**Comment by xrchz** [comment]
@michaelsproul how's it going?

**Comment by michaelsproul** [comment]
I gave up on this for a while because of the lack of semantics for FFI divergence, but have been thinking about getting it going again now that Johannes has fixed that

**Comment by xrchz** [comment]
@IlmariReissumies @michaelsproul could we get this finished soon do you think?

**Comment by michaelsproul** [comment]
Work in progress branch is here: https://github.com/CakeML/cakeml/compare/master...michaelsproul:exit-code

Let me know if any of it looks unreasonable

**Comment by michaelsproul** [comment]
I've hit a problem with `whole_prog_spec`. At present, it only talks about `POSTv` post-conditions, yet the spec theorem that I proved is in terms of general `POST` (because it can FFI diverge). I can prove a theorem about what happens in the non-error case by adding an assumption, but then that seems to make `whole_prog_thm` choke. The lemma with the assumption that I can prove is:

```sml
val main_whole_prog_spec = Q.store_thm("main_whole_prog_spec",
  `(SND (compile_64 (TL cl) (get_stdin fs)) = strlit "" ∨ has_version_flag (TL cl)) ==>
   whole_prog_spec ^(fetch_v "main" st) cl fs (SOME RUNTIME)
    ((=) (full_compile_64 (TL cl) (get_stdin fs) fs))`,
```

@IlmariReissumies mentioned that @oskarabrahamsson might be doing some work on this to improve the situation for FFI diverging programs. Any and all suggestions welcome!

**Comment by IlmariReissumies** [comment]
Unless and until @oskarabrahamsson does his `whole_prog_thm` refactor, you should be able to derive separate `POSTv` and `POSTf` specs, with preconditions as in your theorem statement above, that you can use with `whole_prog_spec` and `whole_prog_ffidiv_spec`

**Comment by michaelsproul** [comment]
Right, so stuff the assumptions into the pure preconditions?

**Comment by michaelsproul** [comment]
We worked on this offline, but we're still stuck

**Comment by xrchz** [comment]
Could you say more about why you're stuck, or try to get unstuck on Slack?

**Comment by myreen** [comment]
I should mention that have an almost working patch that solves the original topic of this issue, namely to return a non-zero exit code on compiler error. (I’m doing this the quick and dirty route: causing the program to run out of heap space just as it is about to exit).
