### ISSUE TITLE
Support wildcard patterns

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#265]
The CakeML AST and parser do not seem to do anything too special with pattern wildcards (_) - the parser turns them into variables. As a result, declarations with multiple wildcards may fail to typecheck due to duplicate bindings. This could be fixed by either making the parser generate unique variable names or adding a wildcard pattern to the AST.

**Comment by mn200** [comment]
I think the latter is probably better, but I can certainly do the former if there's no desire to change the AST and (presumably) the type-checker.

**Comment by xrchz** [comment]
@SOwens what do you think of adding wildcard patterns?

**Comment by mn200** [comment]
And, it's not just declarations that can fail; case expressions also have patterns that might include multiple underscores.

**Comment by SOwens** [comment]
It doesn’t sound too hard. I’ll look into it.

Scott

**Comment by SOwens** [comment]
I'm assigning the issue to mn200 for the parser update, but the cf stuff needs to be updated too.

**Comment by xrchz** [comment]
@Armael can you figure out how to update CF for wildcard patterns?

**Comment by xrchz** [comment]
My guess would be `v_of_pat envC Pany insts = SOME (ARB, insts)`

**Comment by mn200** [comment]
Done the parser stuff.  (Strictly not the parser but rather the conversion from parse tree to AST.)

**Comment by Armael** [comment]
Looking at this. @xrchz guess is probably right.

**Comment by Armael** [comment]
Umm, actually, it wouldn't work. We want the following theorem to hold:

```
      pmatch envC s pat v env_v = Match env_v' ==>
      pat_without_Pref pat ==>
      ?insts.
        env_v' = ZIP (pat_bindings pat [], REVERSE insts) ++ env_v /\
        v_of_pat envC pat insts = SOME (v, [])
```

So `v_of_pat envC Pany insts` cannot return `ARB`, it must return the value `v` that would be matched against the pattern… But then `env_v' = ZIP (pat_bindings pat [], REVERSE insts) ++ env_v` entails that `insts` is `[]`...

**Comment by Armael** [comment]
A solution might be to have an additional `wildcard_insts` parameter to `v_of_pat`, that gives the instantiations for the wildcards.

**Comment by xrchz** [comment]
@Armael would you be able to try that out?

**Comment by Armael** [comment]
Done! (https://github.com/CakeML/cakeml/pull/273)
