### ISSUE TITLE
Holmake will randomly break

### ISSUE THREAD

**Issue by Holmus** [CakeML/cakeml#268]
Occasionally when running Holmake it will fail due to a whitespace unexpected error. The locations are seemingly random and you can force your way through it by running Holmake again.

It seems to be a concurrency issue and a workaround is either to force through by running Holmake again or by using Holmake with the -j1 flag.

Example errors, note that --fast is being used as a flag here, hence the output "CHEATED":
```
Finished recursive invocation in /home/holmus/projects/DATX02/cakeml/compiler/encoders/asm
bvi               | bvl               | dataLang          | Holmake failed with exception: LEX_ERROR "clos_freeScript.sml 62.7 '.'-whitespace unexpected"
```
```
Finished recursive invocation in /home/holmus/projects/DATX02/cakeml/compiler/encoders/asm
data_simpTheory                                                              OK
data_liveTheory                                                         CHEATED
data_spaceTheory                                                        CHEATED
bvi_letTheory                                                           CHEATED
bvl_constTheory                                                         CHEATED
bvl_jumpTheory                                                               OK
bvl_inlineTheory                                                        CHEATED
clos_freeTheory                                                         CHEATED
bvl_handleTheory                                                        CHEATED
clos_annotate     | clos_call         | clos_known        | Holmake failed with exception: LEX_ERROR "clos_mtiScript.sml 16.36 '.'-whitespace unexpected"
```

**Comment by xrchz** [comment]
This is probably due to stale unfinished theory files lying around (from previous failed builds) for which `Holmake` fails on reading when scanning for dependencies. Just a guess.

**Comment by xrchz** [comment]
I'm also running into random failures. The randomness makes it very hard to figure out why...

**Comment by xrchz** [comment]
You may find the `-k` flag to `Holmake` helpful in working around this.

**Comment by Armael** [comment]
I'm also getting this error quite often, even after a `git clean -xfd`.

**Comment by xrchz** [comment]
I seem to get these errors much more often now with polyml 5.7.

**Comment by xrchz** [comment]
Some investigation using the `stress` tool on Linux suggests that this is highly dependent on memory load. If I run `stress -m 8` the chance of `Holmake` dying seems to go up. This is true on both 5.6 and 5.7.

**Comment by xrchz** [comment]
This is a HOL issue rather than a CakeML one. I created HOL-Theorem-Prover/HOL#461 to track it there.
