### ISSUE TITLE
implement stackLang to stackLang transformations

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#29]

**Comment by xrchz** [comment]
@myreen: What are these transformations?

**Comment by myreen** [comment]
They are:

1. introduce the GC implementation into the stubs i.e. remove Alloc, *not implemented yet*
2. [remove stack operations, i.e. make them memory accesses](https://github.com/CakeML/cakeml/blob/new_compiler/compiler1/stack_removeScript.sml)
3. [renaming variables to match the actual target registers names](https://github.com/CakeML/cakeml/blob/new_compiler/compiler1/stack_namesScript.sml)

Implementing 1. will depend on the GC function used for the proof of the bvp-to-word compiler.

**Comment by xrchz** [comment]
@myreen is this done?

**Comment by myreen** [comment]
Yes
