### ISSUE TITLE
Support composition of CF-verified functions

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#291]
This issue is to ensure that function composition (o) is usable in CF-verified programs that inherit the basis library. (I don't know if it means `o` needs to be translated specially at some point and added into one of the basis library prog scripts, or if an existing translation needs to be properly exposed, or something else.)

**Comment by xrchz** [comment]
Update: composition is there, but the problem is using it with impure functions. This is a special case of the standard problem with higher-order CF. (For only pure functions, the translator should be used instead.)

**Comment by tanyongkiam** [comment]
Not fixing for current CFML.
