### ISSUE TITLE
Swap tag values for true and false

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#298]
Currently, `true` is represented as `Block 0 []` and `false` as `Block 1 []`. These ought to be the other way around as the current representations cause sub-optimal code in `data_to_word`.

**Comment by xrchz** [comment]
Where is the sub-optimal code and how should it be changed?

**Comment by myreen** [comment]
See the comments in the following:
https://github.com/CakeML/cakeml/blob/float/compiler/backend/data_to_wordScript.sml#L1352
Note this is on the `float` branch.

**Comment by xrchz** [comment]
OK, so it's clear what to do on the `float` branch (delete some lines of code). Just to check: the existing code on `master` should be modified as little as possible just to get things to work again with the swapped tags?

**Comment by myreen** [comment]
Yes
