### ISSUE TITLE
to_word32Prog can't compile?

### ISSUE THREAD

**Issue by jiamo** [CakeML/cakeml#311]
Do it by  https://github.com/CakeML/cakeml/blob/master/build-instructions.sh

Finished recursive invocation in compiler/inference/proofs
to_word32Prog   162 to_word64Prog    15
to_word32Prog   162 to_word64Prog    15
to_word32Prog   162 to_word64Prog    15

to_word32Prog   163 to_word64Prog    15
to_word32Prog    35 to_word64Prog    52
to_word32Prog    35 to_word64Prog    52
to_word32Prog    19 to_word64Prog   128
to_word32Prog    19 to_word64Prog   129
to_word32Prog    20 to_word64Prog   129
to_word32Prog    16 to_word64Prog   164

The compile process can't stop. (The lines was created by press `enter` when it is compiling)

**Comment by tanyongkiam** [comment]
Hi,

That is building the translation of the CakeML compiler in preparation for
the bootstrap evaluation.

It can take awhile (upwards of a few hours), depending on what kind of
machine you have.

Those lines you are seeing indicate that it's making some progress.

**Comment by jiamo** [comment]
Ok.  My machine is mac pro 2015 version with the i7 process.
The time this step takes is not normal like other steps. 
New to cakeml.  I think `to_word32Prog   and  to_word64Prog` may need to take a look at.

**Comment by tanyongkiam** [comment]
Yeah, the counter is reset each time a new theorem is stored during the
run. That's fine, you just have to leave it for a longer time.

You'll see the same phenomenon, e.g. in the backend/proofs directory.

Do you need to build the full bootstrap of the compiler yourself? We have
copies of the compiler available online at https://cakeml.org/download

**Comment by xrchz** [comment]
Anything further required here, or can I close it?

**Comment by jiamo** [comment]
no more.
