### ISSUE TITLE
Reorder bootstrap translation

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#317]
`to_data` is the phase that usually changes, but one has to wait for the lexer, parser, etc. before getting to it. These could be translated later instead.

**Comment by xrchz** [comment]
Here is the current order: `basis` -> `lexer` -> `parser` -> `infer` -> `reg_alloc` -> `to_data` -> ...

To be clear, what is the desired order? (@myreen probably has an opinion)

**Comment by myreen** [comment]
My preference is to have `to_data` as early as possible, i.e.

`basis` -> `to_data` -> `lexer` -> `parser` -> `infer` -> `reg_alloc` -> ...

The other parts (excluding `basis`) seem to change infrequently.
