### ISSUE TITLE
Add a help/usage message to the compiler

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#319]
Make the bootstrapped CakeML compiler accept a `--help` option which prints helpful informative output, and add a usage message in case of bad usage. Probably depends on #248 to do it right.

**Comment by myreen** [comment]
In addition, one could make the bootstrapped compiler read its input from a file and write its normal output to a file.

**Comment by lorenzleutgeb** [comment]
The help text should mention the unit of measure for numeric arguments such as stack size and heap size.

**Comment by xrchz** [comment]
It seems like this has been done since 76ed0b05089a77059dee72d197fc56c3dae661e8
