### ISSUE TITLE
Print error message on resource limit hit

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#322]
Make compiled programs (including the bootstrapped compiler) print an informative message on `stderr` when it gives up due to hitting a resource limit. May be related to #260.

**Comment by xrchz** [comment]
@tanyongkiam says  https://github.com/CakeML/cakeml/blob/master/basis/basis_ffi.c#L106 you can add an error message by printing out based on the exit argument here

**Comment by tanyongkiam** [comment]
see also https://wiki.cakeml.org/startup-halting

**Comment by tanyongkiam** [comment]
#721 will close this issue
