### ISSUE TITLE
Bootstrap the compiler on MIPS

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#325]
The bootstrapped compiler is currently built for the `x86-64` and `riscv` targets only. This issue is to create theories to perform the bootstrap translation and compilation for the `mips` target. To start, look at what is done in `compiler/bootstrap/translation` and `compiler/bootstrap/evaluation` that is, say, `riscv` specific, and make a `mips` version.

**Comment by tanyongkiam** [comment]
Additionally, there is also a need to update the wrapper in mips_exportScript to do the right thing (it hasn't been updated for the new interface).

**Comment by tanyongkiam** [comment]
I have added a preliminary version of the mips export script, but it isn't clear that it has the right behavior.

**Comment by xrchz** [comment]
@tanyongkiam is this done now?

**Comment by tanyongkiam** [comment]
There's a cross compiler (built on x64) targeting MIPS. However, I still don't think the export script has the right behavior (and I can't really test it).

**Comment by xrchz** [comment]
I think the cross compiler you made is all I wanted out of this issue.
