### ISSUE TITLE
Make the bootstrapped compiler a cross-compiler

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#326]
This issue is to add compiler command-line flags to the bootstrapped compiler which let the user choose the compilation target. Most of the bootstrap translation is shared: only the encoders differ, at least for the 64-bit targets. For this issue, 32-bit ARM can be left out. The compiler that takes the target flags should then be bootstrapped for each target.

**Comment by tanyongkiam** [comment]
This is closed by #352 (for the 64-bit targets):
./cake --targetx64 < foo.sml > foo_x64.S
./cake --targetarm8 < foo.sml > foo_arm8.S
./cake --targetmips < foo.sml > foo_mips.S
./cake --targetriscv < foo.sml > foo_riscv.S
