### ISSUE TITLE
Automate testing pull requests

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#333]
Currently, we have automated regression tests running on Bamboo for `master` - whenever there are new commits - and manual regression testing of branches also on Bamboo. There is no easy way to run a test of a fork on Bamboo, and also nobody can access/configure the Bamboo setup except @xrchz. This issue is a request to improve this situation. The following are desired.

1. Regression tests of `master` run whenever anything changes (in HOL or CakeML) to catch bugs.
2. Regression tests of the merge of any pull request with master run _automatically_.
3. The regression test infrastructure can be accessed/modified by any CakeML developer.
4. The tests send email to `builds@cakeml.org` with their results.

Proposals for how to achieve any of these? Can we write enough machinery ourselves that the desired functionality can be easily deployed on any spare machines?

**Comment by hferee** [comment]
I guess travis resolves most of these points. Why was it abandoned in the first place?

**Comment by hferee** [comment]
Oh, for the time limit I guess.
But this can be circumvented on a local machine.

**Comment by xrchz** [comment]
Do you have a local installation of Travis on which to test that out? My impression was that it has a global time limit of 2 hours no matter what.

**Comment by hferee** [comment]
No, I just have been playing with the official instance. I could try to install it later though.
The doc says that there is no timeout for builds, only for jobs (50 minutes or 10 minutes without output), which means we could try splitting the regression test in smaller pieces.

**Comment by xrchz** [comment]
buildbot.net also looks interesting - less bloated, could be configured to exactly what we need. The main bottleneck for us I guess is having machine(s) on which to run the workers. If you can hack travis-ci.org to do the building for us (by splitting builds into jobs under their time limits), although not so elegant, it solves the problem by using their machines.

**Comment by hferee** [comment]
I've tried gitlab-ci, which seems to have user-configurable timeout.
To avoid using gitlab as main repository, we need to find a gitlab instance which supports miroring (mine doesn't), this way the github repo is pulled every hour or so. The main drawback is that we may need to wait 1h for the job to start.

**Comment by xrchz** [comment]
I would consider switching to gitlab for the main repository, actually, (and probably mirroring on github) if it turns out to be much better. There seem to be a lot of positive experience reports about it on the internet. I will look into this at some point.

**Comment by hferee** [comment]
I've tried to split it into jobs for travis-ci, but it's still a beta feature and I can't seem to make it work properly.
I've done the same for gitlab with a runner on my machine. It seems to work fine, although the compilation hangs in compiler-backend-gc
You can have a look at it here:
https://framagit.org/hferee/cakeml/pipelines

**Comment by xrchz** [comment]
Sounds great. Regarding the first con, it should work on any Jenkins instance too, right?

Would it handle PRs from forks too, or only branches?

**Comment by OlympusMonds** [comment]
Yeah, any Jenkins would work (though the email setup in the Dockerfile would have to change). All the hard bits are done anyway.

I used a "Multibranch Pipeline" job in Jenkins to set it up, and it has options for PRs from branches and forks (and testing branches other than master too), as well as if they should test pre or post merge, or both - so should be flexible enough.

**Comment by xrchz** [comment]
This is solved now by https://github.com/CakeML/regression
