### ISSUE TITLE
Global deadcode elimination for flatLang

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#337]
A global deadcode elimination pass in `modLang` (which will soon be called `flatLang`) would, for most compilations, significantly reduce the size of the generated code and also speed up compilation. 

The compiler would become faster because the code it transforms would be smaller. Currently, simple programs such as hello-world programs take an unreasonably long time to compile because the entire basis library is prepended to the user-provided source code before compilation. Having a global deadcode elimination pass would delete everything unused from the basis library.

#336 might serve as a nice starter project leading up to this project.

**Comment by hrutvik** [comment]
This was completed some time ago (b351d072778b4f80ad013d5f67653a82f623b246), and then cleaned up (https://github.com/CakeML/cakeml/pull/553).
