### ISSUE TITLE
Common subexpression elimination in wordLang

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#341]
The `data_to_word` compiler phase maps each abstract operation into a *fixed snippet* of `wordLang` code. A few optimisations are then run on the resulting `wordLang` programs. The optimisations include constant-propagation and -folding, an SSA-like renaming of variables, and register allocation. At present, no optimisation targets the duplication caused by the *fixed snippets* that `data_to_word` produces.

**Example:** The following `dataLang` program loads the first and second part of a `Block`, i.e. a tuple or vector. The source program could be `case foo of (x,y) => ...`.

    v4 := 0;
    v5 := El v4 v1;
    v6 := 1;
    v7 := El v6 v1;

Once `data_to_word`, constant propagation and SSA-renaming has run, the resulting `wordLang` program can look something like the following. Each abstract `El`-primitive has been split into `get_base_addr` followed by a `mem_load` with an appropriate offset.
    
    v12 := get_base_addr(v10);
    v13 := mem_load(v12 + 8);
    v14 := get_base_addr(v10);
    v15 := mem_load(v13 + 16);

Here `get_base_addr(v1)` is duplicated. This duplication is a likely cause of some slowdown since `get_base_addr(v10)` requires a few instructions to implement. A common subexpression elimination phase could rewrite the third line of the code above to `v14 := v12`, which the coalescing register allocator might be able to remove completely.

I propose that a common subexpression elimination optimisation phase is added to `wordLang`. It should be placed after the SSA-like renaming but before register allocation.

This issue is suitable as an MSc thesis topic.

**Comment by tanyongkiam** [comment]
WordLang CSE has been implemented (for a while now), but this issue is now superseded by #966
