### ISSUE TITLE
Make RatProg build on rationals rather than reals

### ISSUE THREAD

**Issue by mn200** [CakeML/cakeml#343]
> In fact the right way would be to define `REAL_TYPE` in terms of a new `RAT_TYPE`. All the current proofs about `REAL_TYPE`’s connection to the `(int, num)` pairs should be modified to talk about `RAT_TYPE`.

**Comment by xrchz** [comment]
#79 is related

**Comment by myreen** [comment]
@xrchz I don't think there is any technical connection between the `Rat` module and support for floats (i.e. #79).

**Comment by mn200** [comment]
Can't this now be closed?

**Comment by xrchz** [comment]
@myreen reopen if you disagree
