### ISSUE TITLE
Improve command-line arguments module

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#347]
Currently the module for command-line arguments and its C counterpart have many annoying restrictions, in particular the combined length of all of the command-line arguments is not allowed to be more than 256.

This issue can be closed once the development around the command-line arguments has been cleaned up and the most draconian restrictions have been lifted.

**Comment by xrchz** [comment]
On this, could we also rename it to CommandLine (with capital L) to match the SML Basis?

**Comment by myreen** [comment]
Sure, I'll do that.

By the way, I've got to a sticky point: the examples currently rely on the command-line not producing names that are longer than 256 characters. Now that the command line arguments can be 65536 characters long (and there can be up to 65536 arguments), the example proofs don't work. I guess the right solution is to dig into TextIO and remove the silly 256 limit.

**Comment by xrchz** [comment]
That's right. You could leave that to me, or just go for it if you're on a roll.

**Comment by myreen** [comment]
I would appreciate it if you looked into removing the limit on file sizes.

I don't think there should be any limit on the length of filenames: one can just allocate an array that's long enough before making the FFI call.

**Comment by xrchz** [comment]
OK I'll look at the TextIO function specs on this branch.
