### ISSUE TITLE
Generate tutorial exercises automatically

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#350]
Currently in `tutorial` there are some "unfinished" theories intended as exercises. The filled in versions are in `tutorial/solutions` and consist of copies of the exercise files with the missing parts filled in. However, these can get out of sync. This issue is to do the following:
- Write automation to generate the exercises from the solutions. (This means clearly indicating in the solutions files which lines to omit as exercises.)
- Make it clear and easy how to generate the tutorial exercises for anyone interested
- ~~Remove the generated files from version control~~
- Move the `wordfreq` and `wordcount` examples to `examples`

Alternatively, we could abandon actually producing exercise files and leave anyone interested in doing the tutorial to just follow the comments in the solutions/examples.

**Comment by IlmariReissumies** [comment]
Why not keep the generates exercises under version control, as we do with lem-generated script files? For the target audience (total beginners), it would be nice if they can look at the exercises without first having to figure out some arcane procedure for generating them.

**Comment by myreen** [comment]
I agree with Johannes. A beginner doesn’t want to first figure out what
script to run in order to see what the exercises are. These generated files
should be in version control.

**Comment by hferee** [comment]
If it means adding special comments around solutions to be removed by a bash script, I can probably do that.

**Comment by xrchz** [comment]
agreed about keeping them in version control (like lem-generated files). I'd rather avoid a bash script if possible (cf. `addancs` in `semantics`).

**Comment by xrchz** [comment]
maybe it would be cool if one of the tutorial examples was a mini `sed` that was also used for this :) I see @hferee has already implemented a version that calls external `sed` - that may be good enough for the moment (the regression tests also depend too much on shell scripts..)

**Comment by hferee** [comment]
Yes, I thought about this ;-)

**Comment by hferee** [comment]
I've got an sml version which is simple enough to be easily translated to cakeml which can just remove sets of lines delimited by special comments.
The issue is I can't fix Holmake to compile the Script files anymore.

**Comment by hferee** [comment]
Fixed, nevermind.
I guess only point 2 remains. Should this be in a simple README file or handled by readme_gen?

**Comment by xrchz** [comment]
It should probably be handled by `readme_gen`, which I think means putting a `readmePrefix` into the `tutorials/solution` directory (and possibly modifying some Holmakefiles)?

**Comment by xrchz** [comment]
I'm happy to leave the readmes to #71 and I might move the examples later (after #354), so this can be closed now.
