### ISSUE TITLE
Use theorem sets for CF specs

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#360]
In `cfTacticsLib`, this function uses `IRULE_CANON` which is rather expensive. I don't believe this is necessary, and using a more efficient method could speed up `xapp`, `xlet_auto`, etc.

Vaguely related to #345

**Comment by mn200** [comment]
It's possible that 

1. the excessive calculations involving free variables in `IRULE_CANON` could be simplified while yielding the same result; or
2. `IRULE_CANON`'s specification could be simplified to not require all those calculations without causing any real usability issues.

**Comment by xrchz** [comment]
Improvements to `IRULE_CANON` sound worthwhile even if we don't end up using it in `is_cf_spec_for`. I think `is_cf_spec_for` should just search for any theorems that include `app`, and the functions that call it should backtrack over them.

**Comment by Armael** [comment]
Indeed. I see two ways of fixing this:
- either reimplement `concl_tm` in a more efficient way; keeping the implicit specification that it returns the subterm that will be matched against the goal when using `irule` (in `xapp_xapply_no_simpl`)
- still use `IRULE_CANON` (since it will be needed when using `irule` later in `xapp_xapply_no_simpl`), but remember it, and thread the result through the code, and in `xapp_xapply_no_simpl` use a version of `irule` that takes the result of `IRULE_CANON` instead of re-computing it...

**Comment by Armael** [comment]
@xrchz searching for any theorem that include `app` would return all the registered specs, and then try `irule` on each of them? This sounds costly.

**Comment by xrchz** [comment]
No I mean search for `app` applied to the correct function. In other words, very similar to what is currently done but without the `IRULE_CANON`.

I think your first option is better than your second. But I'd rather see data on what works best.

**Comment by Armael** [comment]
An other way would be to have a separate mechanism to store CF specifications (other than just `store_thm`), that would maintain a map `term` -> `spec`, which would avoid scanning the whole set of registered theorems at each call to `xapp`.

**Comment by xrchz** [comment]
Yes that is clearly a desirable thing to do. It's easy to create a labelled set of theorems - this is already done for stateful simplifier (`[simp]` attribute) and congruence rule (`[defncong]` attribute) for example. I'd say this issue can be closed if we (a) create a theorem set for CF specs and (b) either remove `IRULE_CANON` from `is_cf_spec_for` or improve the performance of `IRULE_CANON`.

**Comment by mn200** [comment]
Use `ThmSetData.new_exporter`, passing the name of the attribute and the function that will be given new theorems and stores them for later use (presumably in your dictionary).  See for example the bottom of `src/1/DefnBase.sml`.

**Comment by xrchz** [comment]
I think the translator should also be using `ThmSetData` for its certificate theorems, which I wouldn't want to do before #96.

**Comment by xrchz** [comment]
@myreen claims the translator now does this, although not using ThmSetData correctly (not storing only deltas)

**Comment by xrchz** [comment]
Closing the CF version in favour of #813
