### ISSUE TITLE
Include commit hash in bootstrapped compiler

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#373]
It would be good if the bootstrapped compiler had a command-line option (e.g. `--version`) which prints what git commit this bootstrapped compiler was built from.

This could be implemented by including an ML-generated term in some constant definition `current_version`, which gets translated like any other constant. The ML code would ask the shell what git commit the checked out code is at. 

What would the right git command be?

Should this fetching of the current git hash be functionality provided by HOL4? I can imagine that it might be useful in projects other than CakeML. If the HOL4 library wants to be fancy, then it could print what PolyML is currently used, what HOL commit is current, and the commit of the current directory (somewhere in CakeML for us).

**Comment by xrchz** [comment]
A git command to get the current head commit is `git rev-parse HEAD`.

**Comment by oskarabrahamsson** [comment]
This functionality got merged into master with #352.
