### ISSUE TITLE
Translator generates false lookup_cons assumptions

### ISSUE THREAD

**Issue by tanyongkiam** [CakeML/cakeml#374]
In ml_module_demoScript, run DISCH_ALL(hol2deep``Even m``); after closing the module gives:

val it =
   |- Eval env (Var (Short "m")) (NUM m) ⇒
   lookup_cons "Even" env =
   SOME (1,TypeId (Long "Even" (Short "even"))) ⇒
   Eval env (Con (SOME (Short "Even")) [Var (Short "m")])
     (EVEN_TYPE (Even m)):
   thm

The lookup_cons assumption will break, because the constructor is actually behind a module (lookup_cons only looks for Shorts)

This is due to an improper fix (by me) in 1e53ebd.

**Comment by myreen** [comment]
There is a TODO regarding this at the [bottom of ml_translatorLib](https://github.com/CakeML/cakeml/blob/master/translator/ml_translatorLib.sml#L3930):

    TODO
    - ensure datatypes defined in modules can be used outside a module
      (the type thms need to be reproved)

**Comment by oskarabrahamsson** [comment]
I have started to work on this issue on the [translator-module-ctors](https://github.com/CakeML/cakeml/tree/translator-module-ctors) branch.

**Comment by oskarabrahamsson** [comment]
This was solved with #512.

**Comment by oskarabrahamsson** [comment]
Yes, this particular issue is solved: `lookup_cons` previously only did lookups using `Short` names, so it was impossible to translate a function which pattern matched on constructors that were living inside a module. But something else is clearly still broken if `Dtype` declarations in the generated program are wrong.
