### ISSUE TITLE
Add a silent FFI call

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#385]
To allow for tracing/logging etc., it would be nice to have a built-in FFI call that has no observable semantics from CakeML (i.e., always succeeds with no state change, without requiring additional assumptions on the oracle).

**Comment by tanyongkiam** [comment]
Could we do this in a way that does not case on the FFI name explicitly? e.g. making all the FFI names be string options instead?

**Comment by xrchz** [comment]
Sure. Why?
