### ISSUE TITLE
addancs is not robust

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#386]
Either the addancs program or the way the Holmakefile calls it or both leave something to be desired. Here are things I have seen going wrong:
- The addancs program doesn't get called when it needs to be because only a different `.lem` file was modified, not the direct dependency of the Script that needs addancs
- An additional ancestry line gets added mistakenly on a file that already has one. (Maybe this only happened because I tried changing the `Holmakefile` -- no, I can confirm it happened with unmodified `Holmakefile` too.)

This issue is to make the setup more robust, and more obviously so, probably by making the program idempotent and running it under more circumstances.

#177 is related, and #381 should wait for this.

**Comment by mn200** [comment]
What is the test that indicates that this can/can‘t be closed?

**Comment by xrchz** [comment]
Will close this presuming fixed. If it shows up again I'll try to produce a test case.
