### ISSUE TITLE
collect benchmark programs

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#39]

**Comment by xrchz** [comment]
Anthony has given me the SML code generated for the MIPS machine model by L3 as a potential example program to use.

**Comment by xrchz** [comment]
@myreen Can we call this done, given our small suite of programs (`qsort`, `btree`,`fib`, etc.)?

**Comment by SOwens** [comment]
I think we need a much more extensive benchmark suite. Whether that should be another issue or this one, I don't really care.

**Comment by xrchz** [comment]
The trouble with this kind of issue is that you never know when you're done. There could always be another benchmark program, right? Could we make this issue more specific, by having a list of target benchmarks, or a number (say 10) after which it can be considered done?

**Comment by myreen** [comment]
I agree with @xrchz, issues should have a clear target. 

We now have a small collection of useful benchmark programs. I will close this issue.

I encourage @SOwens and others to make new issues for each new set of benchmarks that he or others propose. The important thing is that there is a clear end to each issue.
