### ISSUE TITLE
Bootstrap the compiler by verified interpretation outside the logic

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#393]
The aim here is to speed up the bootstrap compilation without losing the theorem about the final verified machine-code implementation. The scheme is outlined in these emails:
https://lists.cakeml.org/pipermail/developers/2017-February/000178.html
https://lists.cakeml.org/pipermail/developers/2017-February/000180.html

Depends on #392

**Comment by tanyongkiam** [comment]
It doesn't strictly need to depend on #392. You might get away with something like:

val ast = ... translated AST
val _ = print (evaluate ast)

The disadvantage is that big AST term that has to be compiled, but at least it's just lots of constructors and not all the functions in the compiler.

**Comment by xrchz** [comment]
Unnecessary now that we have cv_eval bootstrap speed
