### ISSUE TITLE
Improve xhandle interface

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#400]
I think `xhandle` requires the user to provide a postcondition for the body of the handle expression before any exceptions are handled. This is asking for too much: it's obvious in the case that no exceptions are raised by the body that the postcondition should be the same as the postcondition for the whole handle expression. Thus `xhandle` should only require the user to provide a postcondition for when an exception is raised (to be used as the precondition for the handle's match).

**Comment by tanyongkiam** [comment]
This won't be fixed for CFML but it should be done properly in #813
