### ISSUE TITLE
Add profiling calls to the bootstrapped compiler

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#407]
Each major phase of the compiler should call the empty FFI with a message indicating that it has finished its compilation phase. Currently, this can be done using the `silent_ffi` HOL function -- the translator will target the correct FFI call. This issue is to:

- Move and rename the `silent_ffi` function into somewhere in `basis/pure`, probably `empty_ffi`
- Add a logging call to each major phase of the compiler (probably best to do this in `backendTheory`)

**Comment by myreen** [comment]
It seems wasteful to have a theory containing only one very simple function
definition. Could the function be in mlstringScript.sml?

**Comment by xrchz** [comment]
Sure. Maybe with a comment saying what it is.
