### ISSUE TITLE
Support large heap+stack on 64-bit targets

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#424]
Currently if you try to make a heap+stack bigger than 4GB, you will run into relocation errors due to symbols being only 32 bit values by default.

On `x86_64` this can be fixed by using `movabs $cake_end` rather than `leaq cake_end(%rip)` in the template `.S` file, and compiling with `-mcmodel=medium`.

On `riscv` this can probably be fixed by using `.option pic`  before the `la`.

This issue is to update the templates and/or `Makefile`s to support large heap+stack.

**Comment by myreen** [comment]
For those who wonder where the templates are: the x64 one is
[compiler/backend/x64/export_x64Script.sml](https://github.com/CakeML/cakeml/blob/master/compiler/backend/x64/export_x64Script.sml). Replace `x64` by `riscv`, `arm6`, etc. to find the other templates. The `x64` template is the most important one at present. 

When trying to find a `.S` template that works, I suggest just manually editing the `cake.S` of the bootstrapped compiler https://cakeml.org/cake-x64-64.tar.gz until a solution is found, then editing [compiler/backend/x64/export_x64Script.sml](https://github.com/CakeML/cakeml/blob/master/compiler/backend/x64/export_x64Script.sml).

**Comment by tanyongkiam** [comment]
On platforms where dynamically allocated memory is needed, this could be controlled with a flag to the top-level (bootstrapped) compiler like --dynamic or something like that. The export scripts can take a flag and generate a template with either dynamic memory allocation or static memory allocation.

**Comment by sorear** [comment]
We seem to have switched to malloc at startup for memory allocation, so I think this can be closed?

**Comment by tanyongkiam** [comment]
I agree, closing it.
