### ISSUE TITLE
implement instruction selection in wordLang

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#43]

**Comment by xrchz** [comment]
An email from @myreen to @tanyongkiam:

The simplest spec is that instruction selection should remove all
word_exps from the program. In particular, all

    Assign num ('a exp)
    Store ('a exp) num

must be compiled into `Seq (Inst ..) (Seq (Inst ...) ...)`, and
similarly every

    Set store_name ('a exp)

has to become:

    Set store_name (Var reg_name)

Those are the requirements, then there are various tweaks and smarts
one can add to make it clever. Maybe it's best to start with a simple
approach and then add clever things later. Don't know, it's up to you,
if you want to have a go at this!

(So where can one be clever: rearrange operations to minimise the
number of instructions, e.g.

    (4w && r) && 5w --> r && (4w && 5w) --> r && 4w

One can also add a bit of expansion of Assigned variables followed by
common subexpression elimination to find the ideal instructions to
produce. It's hard to have a compiler that always produces
high-quality instruction selection. Maybe these smarts could be
separate from a straightforward instruction selection pass.)

**Comment by myreen** [comment]
I should add that all the generated `Inst`s must be `inst_ok` as defined [here](https://github.com/CakeML/cakeml/blob/new_compiler/targets/asm/asmScript.sml#L176), but where `reg_ok_def` [here](https://github.com/CakeML/cakeml/blob/new_compiler/targets/asm/asmScript.sml#L140) should simplified to true at this stage of the compiler.

**Comment by tanyongkiam** [comment]
A simple scheme (that can be separated from inst select):
wordLang semantics supports a list of args for commutative operations, e.g.:

Op Add [Const 1;Op Minus [Const 3;Const 2];Op Add [Const 4;Const 5]]

We can add a flattening pass that pulls everything inside the list with the same op up:
Op Add [Const 1;Op Minus [Const 3;Const 2];Const 4;Const 5]]

Then recursively "flatten" the list first:
Op Add [Const (1+4+5); Op Minus ...]

**Comment by tanyongkiam** [comment]
I can't seem to do much for inst_ok except for generating 2 register code so I guess these have to be setup at a lower level (or assumed)

e.g. For memory instructions (pasted here):
` (inst_ok (Mem m r a) c =
     (((m = Load32) \/ (m = Store32)) ==> c.has_mem_32) /\ reg_ok r c /\
     addr_ok a c)`

1) Load/Store32 aren't in wordLang semantics

2) addr_ok gives lower/upper bounds on useable memory addresses but the semantics of (Load exp) in wordLang is to load from the word value of the nested expression -- I guess there needs to be an assumption that such Loads will always be correct (similar problem for aligned access).

Alternative: flatten but don't convert Loads to Insts (i.e. deal with it later) so we only have Load (Var n)

There's a similar problem with arith_ok but those might be handled by tweaking the instructions generated. E.g.: multiple shifts to do a large shift or splitting a large immediate into multiple insts (this works for x64 but I'm not sure for the other targets)

**Comment by myreen** [comment]
I want to clarify that `inst_ok` needs to be true after [stack-names](https://github.com/CakeML/cakeml/blob/new_compiler/compiler1/stack_namesScript.sml) has been applied, where stack-names is a compiler pass that just renames all variables to fit the register names of the target architecture. The stack-names pass assumes that all register names are smaller than `N`, where `N` is the number of actual available register names.

One of the main purposes of the instruction selection pass is to find instructions that are allowed by `inst_ok` (but minus the requirements on specific register names). So what does instruction selection need to do? I'll try to illustrate with a few examples below. The intention is to try to generate code snippets that are as short as possible.

A case where we are lucky:

     a := Load (Add [Const 400w; Var b])
     --->
     Load a (Addr b 400w)

Now suppose `400w` is too large as an address offset, then:

     a := Load (Add [Const 400w; Var b])
     --->
     Add temp b (Imm 400w) 
     Load a (Addr temp 0w)      

Now suppose `400w` is also too large an offset to `Add`, then we can always use `Const` since there is no restriction on the word value in `Const`:

     a := Load (Add [Const 400w; Var b])
     --->
     Const temp 400w
     Add temp temp (Reg b)
     Load a (Addr temp 0w)      

There are other tricky situations regarding add-with-immediate and sub-with-immediate. For example, MIPS doesn't support sub-with-immediate. This means that the instruction selector ought to do the following when translating:

     a := Sub [Var b; Const 400w]

It should try to generate:

     Sub a b (Imm 400w)

If `inst_ok` rejects this, then try:

     Add a b (Imm -400w)

If that fails, then use something like:

     Const temp -400w
     Add a temp (Reg b)

(I intentionally made it `Add a temp (Reg b)` instead of `Add a b (Reg temp)` so that the passes that come after have an easier job when producing two-reg code.)

**Comment by tanyongkiam** [comment]
Optimization to be done:
1) Flatten constants under the same op:
Op Add [Const 1;Op Minus [Var x;Const 2];Op Add [Const 4;Const 5]]
--->
Op Add [Const 10; Op Minus [Var x;Const 2]

2) Actually, also turn Op Minus into Op Add when the RHS is a const:
-->
Op Add [ Const 10 ; Op Add [ Var x; Const -2]] --> Op Add [Const 8; Var x]

3) During inst selection time, this becomes
Add tar x (Imm -8)

if that fails, try
Sub tar x (Imm 8)

If that fails, then use the fallback.

**Comment by tanyongkiam** [comment]
Actually done as of 05ae42fc79573d5cf55e09a10b68f4dbb4905b7f
