### ISSUE TITLE
diffScript contains ugly lemmas with vacuous quantifications

### ISSUE THREAD

**Issue by mn200** [CakeML/cakeml#465]
- `patch_aux_keep_init` : statement begins `!l p t n t' n h t m. ...`
- `patch_aux_keep_init_cons` : statement begins `!l t n t' n h t m. ...`
- `patch_aux_diff_cancel` : quantifies over non-existent `z` variable

**Comment by xrchz** [comment]
Thomas Tuerk has something (possibly included in the Emacs mode) for auto-detecting these kinds of problems, in case it's helpful... I can try to find it if you want.

**Comment by xrchz** [comment]
@IlmariReissumies how's it going?

**Comment by IlmariReissumies** [comment]
I haven't done anything towards this; happy to take a cleanup pass through it.

**Comment by xrchz** [comment]
(The auto-detecting thingy is in the structure `Sanity` btw.)

**Comment by xrchz** [comment]
Fixed in #641
