### ISSUE TITLE
compile away the globals

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#48]
see https://github.com/CakeML/cakeml/issues/45#issuecomment-116963493

**Comment by xrchz** [comment]
Should the semantics of BVI be changed to make explicit that there are no more globals? I'm thinking the `globals` state component should go away. The state relation in the proof should perhaps shift all refs by one and use the first ref for the globals array.

**Comment by myreen** [comment]
Yes, the semantics of BVI (and BVP) should change to only have one
global in the state.

Regarding the state relation, I have already set up the refs to be
sufficiently flexible to deal with the creation of new "hidden
refs". Below I quote the first lines of the state_rel_def. Note how
there needs to be an injective function `b` from the source refs to
the target refs.

    state_rel (b:num->num) (s:bvlSem$state) (t:bviSem$state) <=>
      INJ b (FDOM s.refs) (FDOM t.refs) /\
      (!k. case FLOOKUP s.refs k of
           | NONE => T
           | SOME (ValueArray vs) =>
               (FLOOKUP t.refs (b k) = SOME (ValueArray (MAP (adjust_bv b) vs)))
           | SOME res => (FLOOKUP t.refs (b k) = SOME res)) /\
      ...

**Comment by xrchz** [comment]
To avoid an unnecessary indirection, I'd like to store the globals `ValueArray` directly as the particular value of something in the domain of `t.refs` in BVI, as opposed to storing a `RefPtr` that points to the array. I think this is possible if there is an instruction in BVI that will generate the `RefPtr` pointing to this special location (so I can use that to make the argument to `Deref` etc.). Rather than introduce a real new instruction, I could just change the semantics of, say, `AllocGlobal` in BVI to generate this `RefPtr` (since `AllocGlobal` will no longer be used for anything else). Do you foresee problems with this plan?

**Comment by xrchz** [comment]
Actually, maybe that won't work because there's no way to update the size of the array without the indirection...

**Comment by xrchz** [comment]
The `Ref` instruction in BVI does not support a dynamically determined size for creating a new `ValueArray`. I think that makes this implementation scheme for globals impossible.

**Comment by myreen** [comment]
You're right there needs to be a RefVar instruction in BVI to create the
ref for a given size. The stub needs to allocate a new wide array whenever
the old array becomes too small. I won't be able to support resizing of
arrays in the implementation (without some awful indirections).

**Comment by xrchz** [comment]
Oops I forgot there's already a `RefArray` command. I can use that.

**Comment by xrchz** [comment]
The current size of the globals array can be obtained with `Length` but the number of allocated globals also needs to be stored at runtime, to know when the size limit has been reached and a new array is needed (and what the new size should be). I intend to store this number next to the pointer to the array.

A question: would it be worthwhile changing `closLang`'s `AllocGlobal` instruction to take an argument (the number of globals to allocate), to allow adding to, instead of repeatedly incrementing, the counter of allocated globals? This would make it more like the allocation instruction in the source semantics.
