### ISSUE TITLE
Document compilationLib better

### ISSUE THREAD

**Issue by tanyongkiam** [CakeML/cakeml#487]
It currently uses a bunch of conversions, which makes it really difficult to tell which rewrites are supposed to happen at each step.

For example:
https://github.com/CakeML/cakeml/blob/master/compiler/compilationLib.sml#L275
https://github.com/CakeML/cakeml/blob/master/compiler/compilationLib.sml#L444

**Comment by dnezam** [comment]
Closing, as `compilationLib` has been removed in #1097
