### ISSUE TITLE
Document the fact that compilation time is very long

### ISSUE THREAD

**Issue by xuanruiqi** [CakeML/cakeml#490]
CakeML takes a rather long time to compile. I tried compiling it on my laptop and it ran for more than 15 hours without finishing. 

My processor is a relatively new one and a relatively powerful one for a laptop (Intel Core i7-6700HQ, 2.60GHz). Moreover, it consumes a lot (~8-10GB) of memory, so I can't really use `-j 2` or `-j 4` to speed compilation up.

I can see why compilation is very slow. However, it might be a good idea to document explicitly that compilation is very slow & very memory consuming in the README so that users would have an expectation.

**Comment by xrchz** [comment]
This used to be in the README. I can't find when it got deleted... somewhere in the switch to the new generated README system probably...

**Comment by xuanruiqi** [comment]
I thought it would be a good idea to add that back in, then...
