### ISSUE TITLE
implement and verify parallel move

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#52]
The formalisation is to go into file:
https://github.com/CakeML/cakeml/blob/new_compiler/reg_alloc/parmoveScript.sml
and preferably follow:
http://gallium.inria.fr/~xleroy/publi/parallel-move.pdf

The general formalisation will be used as part of the word-to-stack compiler, but it is to be general enough not to be tied to the compiler definitions.

**Comment by xrchz** [comment]
Should the formalisation be general enough to accommodate multiple temporaries, or should we assume just one temporary?

**Comment by myreen** [comment]
In its current form, the word-to-stack compiler can only give the parallel-move compiler one temporary. Initially, I sketched a compiler that tracks liveness of variables to give a non-empty list of temporaries to the parallel-move compiler, but decided it was too much hassle for what its worth.

I thought the verified function in the paper is using only about one temporary, which is fine.

By the way, once the basic algorithm is verified, as described in the paper, I think we should add a bit of preprocessing to algorithm so that some problematic parallel moves get compiled to nice moves. For example, the paper's conclusion section mentions that `(v3,v2,v1) := (v1,v1,v2)` comes to 4 moves, even though it clearly could compile to three. Here's a simple preprocessing step that can make the normal algorithm do the right thing: filter out assignments to variables that aren't read (in this case v3), put these assignments (i.e. `v3 := v1`) first and replace all right hand sides with the new location. In this case: `v3 := v1` is separated from the rest `(v2,v1) := (v3,v2)`. The normal algorithm is only run on `(v2,v1) := (v3,v2)`. With this separation of the easy cases + substitution, we get the ideal: `v3 := v1; v1 := v2; v2 := v3`.
