### ISSUE TITLE
Create byteTheory and move it to HOL

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#521]
This issue is about:

- collecting all byte-access functions and theorems about them into a new `byteScript.sml`;
- tidying up that file;
- moving it to HOL.

By "byte-access functions" I mean functions such as `set_byte` and `get_byte` in [wordSem](https://github.com/CakeML/cakeml/blob/645d4af010862abf8d2245a879b09d51e48d9afc/compiler/backend/semantics/wordSemScript.sml#L61), and also conversions between words and lists of bytes.

**Comment by xrchz** [comment]
This is pretty related to #549

**Comment by xrchz** [comment]
Many properties of these functions that appear across the CakeML proofs have `good_dimindex(:'a)` as an assumption. However, I don't think `good_dimindex` should appear in this `byteTheory`. What do you think @myreen?

**Comment by myreen** [comment]
@xrchz I agree that `good_dimindex` shouldn't feature in `byteTheory`. However, one might still have theorems for 32 and 64 cases in `byteTheory`.

**Comment by xrchz** [comment]
It's probable that these theorems could/should be generalised. E.g., maybe they work for any word size above 8, or any multiple of 8. I guess this issue should include attempting to generalise theorems if possible, so that more can be put in `byteTheory`.

**Comment by xrchz** [comment]
This is done right? I see byteTheory in HOL now.
