### ISSUE TITLE
astPP should end expressions with semicolons

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#54]
because CakeML concrete syntax currently requires that to be parsed back in

**Comment by mn200** [comment]
See also comments on #25 for more on semicolons.

**Comment by xrchz** [comment]
Good point: this issue could be closed by instead making CakeML not require semicolons everywhere!

**Comment by tanyongkiam** [comment]
I think I can fix this quite easily but just to confirm -- did you mean semicolons after declarations like:

val x = 5;
val y = z;
etc.?

**Comment by xrchz** [comment]
I think that is what Konrad wanted, but you could ask him on the mailing list thread about it. Presumably it would be easy to undo too - I guess just passing a different separator to `printTuple` in various places?

**Comment by xrchz** [comment]
Is this fixed (by e8008032f8cf378e4c92a38e3eb5bb116a0dd4d9)?

**Comment by tanyongkiam** [comment]
Yes, I'm waiting for Konrad to check if the new behavior is what he needed.
