### ISSUE TITLE
Require length of Loc and Jump encodings to be independent of offset

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#544]
Currently the `lab_to_target` pass contains a recursive functions with a clock that can signal that the compiler should give up. 

https://github.com/CakeML/cakeml/blob/40f98cae72e53b495c7ceaa55a79362a94c7cd45/compiler/backend/lab_to_targetScript.sml#L236-L244

This function should not be recursive and should not use a clock. 

To remove the clock, one needs to assume that the length of encodings of `Loc` and `Jump` are independent of the label/jump offset. Concretely, `enc_ok_def` should change:

https://github.com/CakeML/cakeml/blob/40f98cae72e53b495c7ceaa55a79362a94c7cd45/compiler/encoders/asm/asmPropsScript.sml#L25-L43

and the implementation and verification of `remove_labels` should make use of the change.

**Comment by tanyongkiam** [comment]
Could you sketch how the offset_monotonic condition should be used in lab_to_target?

From what I'm reading, isn't it still possible that the length of a Jump/Loc instruction could increase when w1 increases to w2 and that could require another loop around in remove_labels?

**Comment by myreen** [comment]
I'd like it to be:

    offset_monotonic enc c a1 a2 i1 i2 <=> 
    (asm_ok i1 c /\ asm_ok i2 c ==> LENGTH (enc i1) = LENGTH (enc i2))

I think `offset_monotonic` should be renamed to `enc_length_ignores_offset` or similar.

**Comment by xrchz** [comment]
This should be taken into account by #1080 and is superseded by that.
