### ISSUE TITLE
GitHub Webhook (or similar) for push emails

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#560]
As per https://developer.github.com/changes/2018-04-25-github-services-deprecation/, the service that sends emails to our Commits mailing list when someone pushes to GitHub is disappearing. The suggested replacement is a WebHook (https://developer.github.com/webhooks/) handling the push event and sending an email. This issue is to implement that Webhook (preferably in SML or CakeML), ideally as a standalone CGI (or similar) application that can be run on our server with zero or minimal dependencies.

**Comment by xrchz** [comment]
The GitHub link above suggests this is no longer a problem, i.e., they have provided push email notification despite the deprecation of GitHub services. Let's wait and see the emails just work come February, and close this if so.

**Comment by mn200** [comment]
Curiously, hol-checkins just started to receive commit messages over the last couple of days again.  So, perhaps this is already working.

**Comment by xrchz** [comment]
GitHub has indeed provided the requisite email service.
