### ISSUE TITLE
Add local declaration to source

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#563]
SML has a convenient `local ... in ... end` declaration that can be used to avoid polluting the namespace with names that only have a valuable meaning locally.

This issue is about adding something similar to the CakeML source language. 

The concrete syntax can (should?) be the same as that of SML. However, I would prefer a more liberal abstract syntax for CakeML. Here is the suggested abstract syntax for CakeML's `local` expressed in Lem:

    (* Local: decs and visible names of values, constructors and modules *)
    | Dlocal of list dec * list varN * list conN * list modN

_Side note_: I would have preferred to have a list of type names `list typeN` instead of constructor names `list conN`, but the semantics doesn't carry enough type information to write a semantics for the variant based on type names. It doesn't really matter. _End of side note_

The following is an example of how concrete syntax would parse into abstract syntax. The parser needs to populate the lists based on what names are declared below the `in` in the concrete syntax.

    local
      datatype t1 = A | B;
      fun foo a = case a of A => 3 | B => 4;
    in
      datatype t2 = C;
      fun bar a C = 1 + foo a;
    end;
    
    -- parsing -->

    Dlocal
      [ Dtype ... ; 
        Dletrec ... "foo" ... ;
        Dtype ... ; 
        Dletrec ... "bar" ... ] 
      ["bar"] 
      ["C"] 
      []

I believe such a `local` variant will be useful when restricting which functions are to be exposed from the basis library. It will also be handy when porting HOL light code to CakeML. This feature can also be used to cleanly hide the constructors inside the Candle kernel (in the current absence of signatures).

I will shortly commit a first draft of the semantics for such a `Dlocal`.

**Comment by mn200** [comment]
Clearly the concrete syntax won't be a problem.  I take it you're happy to put exception constructors in the same place as normal ones.  And does the name of the type `t2` need to be mentioned somewhere?

**Comment by myreen** [comment]
@mn200 Good to hear that the concrete syntax won't be a problem.

I haven't looked at the type system, but for the evaluation semantics (`evaluate_decs`) the name of the type `t2` doesn't need to appear anywhere. Exception constructors go in the same list as normal datatype constructors.

**Comment by mn200** [comment]
Sounds reasonable.  Targeting that in `cmlPtreeConversion` will be easy.

**Comment by mn200** [comment]
Concrete syntax is defined in `semantics/gram` and implemented and verified under `compiler/parsing`. (See 9fc5ed255.)

**Comment by talsewell** [comment]
I've tested that locally. I think that the local branch is ready to PR now.

Support for local blocks in ml_progLib is yet to come.

**Comment by talsewell** [comment]
PR is #577 .

**Comment by xrchz** [comment]
#577 is merged.

**Comment by talsewell** [comment]
So, what remains to be done in this area is adding support for this feature to ml_progLib and/or ml_translatorLib. My proposal here looks a bit more like Magnus' original idea:
  - ml_progLib permits an "open-local-scope" which is a bit like "open-module"
  - the matching "close-local-scope" takes a list or other specifier for which constant names are to be exported
  - optional extra: ML_code permits a stack of open blocks rather than just the one, which makes this interface more flexible

This can then be used by implementors in the obvious way, open a block, translate the contents of some logical module, and then clarify on closing what should actually be seen outside.

**Comment by myreen** [comment]
@talsewell I worry that this approach might not work well with CF developed programs, or programs developed with a combination of the translator and CF.

I would not object to an interface that reflects more directly what goes on underneath. 

For modules, `ml_progLib` currently provides:
 - `open_module` --> one can think of this as writing `structure ... = struct`
 - `close_module` --> one can think of this as the `end` of the ML struct

For local, `ml_progLib` could provide similar:
 - `local_begin` --> one can think of this as writing `local` of `local ... in .. end`
 - `local_in` --> one can think of this as writing `in` of `local ... in .. end`
 - `local_end` --> one can think of this as writing `end` of `local ... in .. end`

I can imagine that one might want to have a `local_end_all`, which allows the following pattern: 

    val _ = ml_prog_update local_begin;
    val _ = translate foo1_def;         (* hidden *)
    val _ = ml_prog_update local_in;
    val _ = translate bar1_def;         (* visible *)
    val _ = ml_prog_update local_begin;
    val _ = translate foo2_def;         (* hidden *)
    val _ = ml_prog_update local_in;
    val _ = translate bar2_def;         (* visible *)
    ...
    val _ = ml_prog_update local_end_all;
    (* here only bar1, bar2, ... are visible *)

**Comment by talsewell** [comment]
@myreen OK, I can work more directly with the primitives.

(The interface I described could be built on top in any case.)

This will definitely require adjusting ML_code to handle a list of blocks to be closed rather than just the one we have at the moment. Well, that gives me a job to do.

**Comment by myreen** [comment]
I'm closing this issue because this feature has been implemented, is on `master`, and I have used it without problems on the `basis-cleanup` branch.
