### ISSUE TITLE
User-friendly interface to the monadic translator

### ISSUE THREAD

**Issue by oskarabrahamsson** [CakeML/cakeml#565]
This issue is about making the interface of the monadic translator more user-friendly.

Setting up and using the monadic translator is fairly involved and requires a lot of tedious boilerplate. See e.g. [this example](https://github.com/CakeML/cakeml/blob/master/translator/monadic/examples/floyd_warshallProgScript.sml): this small example requires 50-100 lines of setup. This is worse when compared to the original translator, which requires none.

I would like to propose a new interface where the user performs some _simple_ set-up using a `config` type, and some functions on that type:

```sml
  type config

  val local_state_config : config
  val global_state_config : config

  val with_state : hol_type -> config -> config
  val with_exn : hol_type -> config -> config
  val with_refs : (string * term) list -> config -> config
  val with_arrays : (string * term) list -> config -> config
  val start_translation : config -> unit
```
Here is an explanation:
* `{global,local}_state_config` sets the 'mode' of the translator (previously called 'static' and 'dynamic').
* `with_state` and `with_exn` picks the type of the state-record and the exception type
* `with_{refs,arrays}` gives the names of the fields in the state record that should be marked as arrays/references, along with initial values for these fields.
* `start_translation` takes a config, checks that it is OK, and then executes all  that was previously boilerplate.

Aside from the most needed functionality (`m_translate` and such) this should be all that the user sees. Any ideas, suggestions and improvements are welcome.

**Comment by talsewell** [comment]
So, this might be a bit "big picture" but anyway ... I think that eventually there should just be one translator.

There would be a collection of types configured to cause special-case translation. A function is special-case translated if its return type matches one of the types. Essentially, the "start_translation config" above would be replaced with "setup_translation type config".

So there's a bigger picture idea that's largely orthogonal to everything you said.

**Comment by oskarabrahamsson** [comment]
I agree with @talsewell's idea. 

Here is another comment: I think that when implementing these (or other) changes to the translator, it should be done in a way such that it becomes easier to move to a functional implementation of the translator in the future.

**Comment by tanyongkiam** [comment]
Another thing that would be pretty nice from a user-friendliness perspective is to automatically prove some routine [simp] theorems needed for further proofs.

See for example, the ones listed here for the IRC allocator: https://github.com/CakeML/cakeml/blob/master/compiler/backend/reg_alloc/proofs/reg_allocProofScript.sml#L111

If possible, it would also be nice if there was a monadic library+theorems for working with the lists that represent arrays (e.g., app, map, fold etc.)

**Comment by oskarabrahamsson** [comment]
There is ongoing work towards this issue on the branch [monadic-trans-cleanup](https://github.com/CakeML/cakeml/tree/monadic-trans-cleanup).

**Comment by oskarabrahamsson** [comment]
Closing this as  #618 was merged several years ago.
