### ISSUE TITLE
Running CakeML generated code in Windows

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#581]
The [VeriPhy project](http://www.ls.cs.cmu.edu/VeriPhy/) has expressed an interest to run CakeML generated x64 code under Windows.

This issue is about making that possible and easy. 

The work required is to:
 1. find the differences in C calling conventions between our FFI calls under Linux and Windows
 2. tweak the way CakeML uses registers on x64 so that the callee-saved registers include the registers CakeML relies on being preserved across external calls
 3. figure out how to produce Windows-compatible `.S` files
 4. add a new command-line argument `--windows` to the bootstrapped compiler, which then produces Windows-compatible output

**Comment by tanyongkiam** [comment]
I got a version of this working with the following changes (corresponding to @myreen's list). This is a lightweight patch and might not be the "right" fix:

1) The Windows calling conventions takes its first 4 arguments in a different order. Conveniently, CakeML FFI calls only need 4 arguments. Concretely for x64, this snippet remaps them to the right ones:
```
      movq    %rcx, %r9
      movq    %rdx, %r8
      movq    %rsi, %rdx
      movq    %rdi, %rcx
```
2) I believe the callee saved registers currently used by the x64 configuration is a subset of those that are actually callee saved on Windows so no need for changes here.

3) Currently, the size of each FFI is set to 16bytes https://github.com/CakeML/cakeml/blob/master/compiler/backend/lab_to_targetScript.sml#L13

This needs to be changed to accommodate the aforementioned switch in register mappings (or there needs to be a different x64 configuration passed through the whole compiler).

Alternatively, one can change the generated snippets as follows.

This is the usual snippet:
```
cake_ffiwrite:
     pushq   %rax
     jmp     cdecl(ffiwrite)
     .p2align 4
```
Change it to:
```
cake_ffiwrite:
     pushq   %rax
     jmp     cdecl(windows_ffiwrite)
     .p2align 4

```
Then, AFTER the CakeML program bytes, insert a new block that does the patching up and jmp:
```
windows_ffiwrite:
      movq    %rcx, %r9
      movq    %rdx, %r8
      movq    %rsi, %rdx
      movq    %rdi, %rcx
      jmp     cdecl(ffiwrite)
```
4) This is slightly annoying to set up. I think one needs to make the FFI space in 3) something like 64 bytes or so for this to work nicely.
