### ISSUE TITLE
Lint opens

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#587]
This issue is to extend the linting functionality of `readme_gen` to check the style and contents of `open` declarations in script, library, and syntax files.
In particular, the conventions to check are as follows (to be discussed on this issue if there's contention):
- Exactly one `open` declaration, which must appear after a blank line after the documentation comment.
- The first structure must be `preamble`, and no HOL structures available thereby should appear.

**Comment by tanyongkiam** [comment]
This should be superseded by #1109
