### ISSUE TITLE
Remove "compiler" and "new_backend", rename "compiler1"

### ISSUE THREAD

**Issue by SOwens** [CakeML/cakeml#59]
For putting together the system, we want the compiler in a good place. Also, I think that compiler1 has completely incorporated the contents of compiler and new_backend, but I'm not sure.

**Comment by xrchz** [comment]
There is possibly a little bit of work (e.g., #51) in `new_backend` that hasn't been incorporated into `compiler1` yet. Also, before removing `compiler`, I would like the bootstrap (and the rest of the regression test) to work. So I can imagine `compiler1` replacing `new_backend` soonish, but `compiler1` then replacing `compiler` only after significant new additions. (After `new_backend` is replaced, the two compiler directories could be given better names if you prefer.)

**Comment by xrchz** [comment]
To get `compiler` working again, we also need the old semantics (with left-to-right evaluation). It's possible that this is not worth the effort, so the `new_compiler` branch should just live as long as is required until we have a working bootstrapped REPL for it.

**Comment by xrchz** [comment]
I am removing `new_backend` now. bvl_inline (and anything else that was still required) can be found in b8e4270.
