### ISSUE TITLE
Add FFI to the initial program

### ISSUE THREAD

**Issue by SOwens** [CakeML/cakeml#60]
The problem is that, in the AST's FFI call, which foreign function to call is not computed by a CakeML expression. It is a static part of the AST. So we can't just add a simple function called ffi to the initial program.

Options:
1. Change the semantics of FFI to take an expression computing the call. :(
2. Pick a small concrete set of foreign functions to call (e.g., getChar, putChar), and put each of them in the initial program.
3. Put a limit on the number of FFI calls and put a jump-table function in the environment. For example, something like this, or a more efficient version:
fun ffi n bytes =
  if n = 1 then FFI_1 bytes 
  else if n = 2 then FFI_2 bytes
  else ...

**Comment by xrchz** [comment]
To me, option 3 looks best in the short term (just to get benchmarks, for example), and probably option 2 in the long term (we don't have to add them all at once). Alternatively just do option 2 from the start, on an as-needed basis. Option 1 seems like the wrong interface to be exposing to the programmer.

**Comment by myreen** [comment]
I prefer a variant of option 3:

    fun ffi0 bytes = FFI 0 bytes;
    fun ffi1 bytes = FFI 1 bytes;
    fun ffi2 bytes = FFI 2 bytes;
    fun ffi3 bytes = FFI 3 bytes;
