### ISSUE TITLE
Target official ARM semantics

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#601]
A version of the ARM ISA in Sail has been made available [here](https://github.com/rems-project/sail-arm/tree/master/arm-v8.5-a). This model originates with ARM, so has some form of legitimacy. This issue is to add this model of ARM as a target for CakeML (possibly replacing one or more of our existing ARM targets).

**Comment by myreen** [comment]
Sounds good. A first step would be to get a HOL export from sail into `HOL/examples`.

**Comment by AndreasLoow** [comment]
Just to link the issues: The following issue is related to loading the very large records defined in the current ARM model: HOL-Theorem-Prover/HOL#713. Currently, it takes over two hours to define the large records in the model.

**Comment by IlmariReissumies** [comment]
Closed by #858
