### ISSUE TITLE
make the new compiler evaluate in the logic

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#61]
this probably means finish `compilerComputeLib.sml` or else replace it with some other mechanism.

**Comment by xrchz** [comment]
@tanyongkiam is this done? (or what's the status)

**Comment by tanyongkiam** [comment]
It's done up to lab_to_target -- evaling val x = (fun f x => x) works up to
lab (not all the intermediates are done I think, so the resulting code is
not necessarily correct).

I actually fixed a bug in the eval compset yesterday (I wasn't correctly
adding the monad/sorting defs to the compset) so it now evals through the
allocator much faster (~6s for the above) than my original tests.

**Comment by xrchz** [comment]
@tanyongkiam how about now?

**Comment by tanyongkiam** [comment]
This has been done for awhile already.
