### ISSUE TITLE
document, and possibly rethink, HOLHEAP policy

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#62]
CakeML currently creates many Poly/ML heaps (one in most directories), building on previous heaps. The exact contents of each heap is a bit random, since there is no well-understood policy on what should be listed. Similarly for the parent heap, when present.

As I understand it, the point of heaps is to trade space for time. The point of this issue is to reevaluate our use of heaps, to pick a policy that is likely to save us the most time for common workflows on the repository, and to document that policy (probably at https://wiki.cakeml.org/Conventions).

**Comment by myreen** [comment]
When working with the compiler proofs in compiler1, compiler1/semantics and compiler1/proofs, I find it very useful to have heaps, but to exclude the files that I'm currently working on from the heaps. By excluding the currently changing files, Holmake doesn't rebuild the heaps and loading times are good all around.

**Comment by xrchz** [comment]
Is it possible to somehow get `Holmake` to automatically detect which files are changing, to get this good behaviour without having to edit the `Holmakefile`? Is there some HOLHEAP policy that would give us that behaviour?

Maybe `Holmake` could be made to only update the heap when told (i.e., when we are done editing), but otherwise default back to reloading changing files (but reusing the heap for non-changing files).

**Comment by mn200** [comment]
If the files are already present in the heap, then reloading new versions of those same files over the top of them is not sure to work well.

**Comment by xrchz** [comment]
One suggestion (from @tanyongkiam): everything should build _without_ heaps, and heaps should therefore only be an optimisation.

**Comment by xrchz** [comment]
Here's a plan for action:
1. Remove all heaps and get the build to go through.
2. Measure any performance change (e.g., total regression time) to see if it's worth proceeding further.
3. Revive discussion here to settle on a transparent heap policy (i.e., optimisation only, no functional difference, as suggested above).
4. Implement it

**Comment by xrchz** [comment]
The policy for now is "no heaps" unless anyone objects.
