### ISSUE TITLE
Capitalized Candle primitives need new names

### ISSUE THREAD

**Issue by oskarabrahamsson** [CakeML/cakeml#626]
This issue is about inventing new names for all Candle kernel primitives with all-caps names.

For instance, there is both `inst` and `INST`. Since the latter is not valid, the translator attempts to pick the name `inst`. Since this name is already taken by the first function, `inst_1` is picked.

Here are some suggested names based on the type signatures of the functions:
* `REFL` -> `refl_conv`
* `TRANS` -> `trans_rule`
* `MK_COMB` -> `mk_comb_rule`
* `INST` -> `inst_rule`
* ...

**Comment by myreen** [comment]
The name suggestions look good to me.

**Comment by oskarabrahamsson** [comment]
This issue is resolved by #655 and #656.
