### ISSUE TITLE
Implement a `Double` basis module

### ISSUE THREAD

**Issue by HeikoBecker** [CakeML/cakeml#637]
The `Double` basis module should be implemented once #636 has been resolved.
The goal should be to define a basis module `Double` which provides functions for operations over double, including `fromString` and `toString` functions; the double type should be abstract

**Comment by HeikoBecker** [comment]
I have experimented with this locally. 
Adding the primitive operations was straight-forward. For `fromString` I currently use `Word8.toInt` and `Word64.fromInt` to translate the result of an FFI call to `double_fromString`.
Would it be okay to for now not have a `toString` function? Getting the string for a float might require relatively larger buffer sizes on the FFI. Or could the length of the string returned by `toString` be limited?

**Comment by myreen** [comment]
I would like support for `toString`. Can one not ask the output of some float-to-string C library function to be at most 255 characters? (The CakeML side of the implementation would then allocate a 256 byte array, ask the FFI to write to the byte array (with a representation ending in 0), and then copy the relevant part of the array into an ML string using the CakeML primitive for doing such copies).
