### ISSUE TITLE
Add encodeLib to build sequence, or delete it

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#642]
`compiler/encoders/tests/` is never used anywhere and does not work. It should be turned into a test theory that can be run as part of the regression test and added to the build sequence. Or if that is not desired, it should be deleted.

**Comment by xrchz** [comment]
@acjf3 how could this be tested?

**Comment by dnezam** [comment]
Closing in favor of https://github.com/CakeML/cakeml/issues/1116 which aims to locate these files automatically and thus applies more generally.
