### ISSUE TITLE
Get CakeML on Try It Online (tio.run)

### ISSUE THREAD

**Issue by hrutvik** [CakeML/cakeml#652]
@larsrh mentioned getting an interactive "try writing CakeML" feature somewhere online. Try It Online (https://tio.run/) has 638 languages (practical and recreational) available to try interactively in the browser. From their GitHub readme, it seems the code is sent off to a server and executed in a sandboxed environment using SELinux, so this should work with CakeML.

We could perhaps:
 - Get in touch with the TIO team about getting a pre-built version on their server
 - Put a link to this somewhere on our website

Thoughts welcome!

**Comment by xrchz** [comment]
Sounds great! Would you be happy to contact them requesting the addition? One thing to check is whether they accept updates of the compiler and how easy that is (because otherwise we should pick a particularly good version to send).

**Comment by hrutvik** [comment]
See [here](https://tio.run/#cakeml) for CakeML on TIO!

One of their team says this about updates:
> I can update CakeML as frequently as you want, but the process isn't automated yet.
> 
> Whenever I should re-run the setup script, someone would have to let me know, in https://talk.tryitonline.net, https://gitter.im/tryitonline/Pull or via email.

The relevant email address is feedback@tryitonline.net.
