### ISSUE TITLE
Runaway stream evaluation causes segfault

### ISSUE THREAD

**Issue by laMudri** [CakeML/cakeml#66]
Running the following code quickly causes a segmentation fault. SML REPLs would usually use up all the memory available and carry on spinning.
```
datatype 'a stream = Cons of (unit -> 'a * 'a stream);

fun map f xs = case xs of Cons xf => case xf () of (x, xs) =>
  Cons (fn u => (f x, map f xs));

fun succ x = 1 + x;
fun pred x = x - 1;

fun nats u = Cons (fn u => (0, map succ (nats ())));

fun index n xs = case xs of Cons xf => case xf () of (x, xs) =>
  if n = 0 then x else index (pred n) xs;

val test_nats = index 1 (nats ());
```
```
[1]    23784 done                cat stream.cml | 
       23785 segmentation fault  ~/cakeml-v1-beta/cake
```

**Comment by xrchz** [comment]
I think this is expected behaviour. When the v1-beta runs out of memory, it will segfault. (The website states this for running out stack, but I wouldn't be surprised if it's also the case for the heap. @myreen would know for sure.)

**Comment by myreen** [comment]
Running out of heap space won't cause a segfault, but stack space is
checked by the OS in v1. Version 2 will check both stack and heap space
internally to the CakeML process.
