### ISSUE TITLE
define source semantics in Lem using functional big step style

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#67]
See discussion on dev list around 2015-09-01, regarding commit 68949a.

**Comment by xrchz** [comment]
One problem with writing in `lem` is that the "real" semantics is what is post-processed by HOL afterwards (namely, after cleaning away the `check_clock` stuff), so if people start from `lem`-generated versions in other theorem provers, they will also have to clean away the clock themselves. I could try writing the "real" version in `lem`, but presumably I'll get unproveable termination conditions. I guess in the meantime I should just write a comment in the `lem` sources.
