### ISSUE TITLE
word_to_target composed compiler

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#68]

**Comment by tanyongkiam** [comment]
I just had a look at stack_to_target (it wasn't actually compiling to target) -- I've fixed that by adding lab_to_target behind the current compile function.

Questions:
1) Do I just keep accumulating the arguments that I'm not sure how to set upwards?

2) What should the form of the program input to word_to_target$compile be? I am guessing it should be either:
A) an alist (arg_count,prog) where I generate the numbering for programs, starting from 2 OR
B) an alist (arg_count,num,prog) where the numbering is passed explicitly

**Comment by myreen** [comment]
Thanks for making stack-to-target actually reach target.
1) Yes. If there are a lot of them, then you might want to define a new record type and put them all in there.
2) a list (alist) where each element is `(name_num, arg_count, prog)`.
