### ISSUE TITLE
Translator chokes on previously translated definitions in local scopes

### ISSUE THREAD

**Issue by IlmariReissumies** [CakeML/cakeml#683]
Consider the following translation:

```
val _ = translation_extends "basisProg";

Definition foo_def:
  foo x = balanced_map$lookup num_cmp x
End

val _ = translate num_cmp_def;
val _ = translate foo_def;
```

The translation of `foo_def` here will fail with the message

```
clean_assumptions: false assumption

⊢ (nsLookup (merge_env appraiser_env init_env).v (Short "lookup") =
   SOME lookup_1_v) ⇔ F
```

The issue seems to be that the translator remembers that it has a `v_thm` about `balanced_map$lookup`, and thus expects it to be present in the environment. However, this is not the case, because in `MapProgScript` the translation of `balanced_map$lookup` is done within the `ml_progLib` equivalent of a  `local ... in` block. Thus the definition is no longer in scope, and the environment lookup will of course fail.

My ideal fix would be that whenever an `ml_prog_update close_local_block` happens, the translator automatically forgets `v_thm`s for out-of-scope names. Barring that, an entry point in `ml_translatorLib` to forget a `v_thm` would be nice.

**Comment by myreen** [comment]
One could add an entry point that tries to prove a lookup-theorem for everything in the translator's list of v-thms. The procedure would filter out the unreachable values from the translator's state. One should at least run this at the end of the basis library, but maybe at every closing of a local scope.

**Comment by myreen** [comment]
Commit 0fa2cdf made the new clean up function run at every export theory. One can also invoke it explicitly with `clean_v_thms`.
