### ISSUE TITLE
Collect compiler backend algorithms into one subdirectory

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#687]
Currently, we have two algorithm subdirectories under `compiler/backend`, namely,
```
compiler/backend/reg_alloc
compiler/backend/gc
```
and the `data-cost` and `pattern_matching` branches are introducing two more:
```
compiler/backend/reachability
compiler/backend/pattern_matching
```
I suggest that we collect the files from all of these under one directory (and its proof directory):
```
compiler/backend/algorithms
compiler/backend/algorithms/proofs
```
Such an arrangement provides more opportunities for `Holmake` to build theories in parallel. Note that the `compiler/backend/gc` currently takes almost 10 minutes to build on `oven2`. This arrangement also reduces the number of directories that only have one or two script files.

**Comment by IlmariReissumies** [comment]
I'm not a huge fan of this idea. I like that the current organisation of subdirectories is more thematically cohesive. Besides, compared to how expensive other parts of the regression tests are, 10 minutes doesn't sound like a big deal either way.

**Comment by myreen** [comment]
@IlmariReissumies Thanks for the good points. OK, let's not do this. I'll close this issue.

**Comment by xrchz** [comment]
Put your pressure on https://github.com/HOL-Theorem-Prover/HOL/issues/382
