### ISSUE TITLE
opentheory wrapper around candle kernel

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#69]
for benchmarking purposes, initially (i.e., in concrete syntax and unverified)

**Comment by xrchz** [comment]
It turns out that doing a version that starts as HOL functions is not much harder, so doing that instead. It's not clear what to verify though: without formalising a specification of OpenTheory, I think the only thing to say is that if you successfully read an article, the resulting theorems are in fact theorems. But this should follow from the kernel soundness (+ the currently missing protected-theorem-type stuff).

**Comment by xrchz** [comment]
Is this done now?

**Comment by oskarabrahamsson** [comment]
Yes. There are still some proofs I might want to clean up in the future, but I think the issue should be closed by #515.

* There is a soundness proof in `readerSoundnessTheory`.
* The monad-io version of the reader separates file I/O, proving, printing. Placing some emptyffi calls in there reveals that the article reader spends around 80 % of its time doing file I/O on the articles I tried out. (Unclear how this scales with larger article files.)
