### ISSUE TITLE
auto-generated readmes

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#71]
generating the readme content from comments in the files in the directory could be one way to avoid it going too stale.

**Comment by mn200** [comment]
The right way to do this would be to write a tool that generates these from the script files, and to then have the directory's Holmakefile try to generate one such in every directory.

**Comment by xrchz** [comment]
@myreen so is this done now?

**Comment by myreen** [comment]
I thought the plan is to only close this issue once practically all files
produce readme entries. Currently hardly any do, but the infrastructure is
there.

**Comment by xrchz** [comment]
Perhaps we could make a list of files/directories that still need READMEs and assign people here?
