### ISSUE TITLE
Double.toString breaks for large floats

### ISSUE THREAD

**Issue by bksaiki** [CakeML/cakeml#725]
Double.toString will abort if it is passed a value larger than or equal to 1e242 because it fails an assertion in ffidouble_toString() in basis/basis_ffi.c:

Source:

void ffidouble_toString (unsigned char *c, long clen, unsigned char *a, long alen) {
  double_bytes d;
  assert (256 == alen);
  for (int i = 0; i < 8; i++){
    d.bytes[i] = a[i];
  }
  int bytes_written = snprintf(&a[0], 255, "%#.12f", d.d);
  assert (bytes_written <= 255);
}

For large values, the current format requires more than 255 characters to completely print out the double. A better format would probably be "%.17g" or even "%.20g" just to be safe.

**Comment by HeikoBecker** [comment]
Thanks for the report. At the time of writing I was not aware of any reasonable defaults here. Will fix now.

**Comment by HeikoBecker** [comment]
This has been merged into master and should be fixed now. I did a very simple test on my machine using clang 7.0.1-8 to ensure that `Double.fromString(Double.toString w) = w` still holds:    

    #include <stdlib.h>
    #include <stdio.h>
    
    int main (void) {
      //Test roundtripping with floating point printing
      double d = 0.0;
      double d_temp;
      char* s = (char *) malloc(256);
    
      for (int i = 0; i <= 100000; ++i)
        {
          snprintf (s,255,"%.20g", d);
          sscanf (s, "%lf", &d_temp);
          if (d == d_temp)
            {
              printf("Success:%.20g\n", d);
            }
          else
            {
              printf("Fail:%.20g\n", d);
              return 1;
            }
          d = d+0.005;
        }
      return 0;
    }
