### ISSUE TITLE
sort out naming in bvl-to-bvi compiler

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#73]
There are a few peculiarities regarding the naming of generated call table entries. 

By the way, the bvl_to_bvi compiler should leave all names 0..99 unused, so that phases below BVI can use these names for their stubs.

**Comment by xrchz** [comment]
That number (99) should ideally be a parameter either defined as a constant in `bvl_to_bviScript.sml` (or similar), or part of the compiler's configuration (i.e. an argument). There is similar stub location reservation happening around `closLang`, so it's probably worth looking at how it is done there.

**Comment by myreen** [comment]
This shifting up is easily implemented by increasing `num_stubs` to `102`. The proof should go through as before. I've made this tweak and it'll be part of my next commit.

**Comment by myreen** [comment]
This should now be fixed in 8755249.
