### ISSUE TITLE
missed optimization: in-place use of CurrHeap

### ISSUE THREAD

**Issue by sorear** [CakeML/cakeml#796]
A current no-basis compiler has 80000 references to the register holding CurrHeap.  Since store values cannot be directly used as inputs to instructions, this is always copied out before being used (typically by an add), at a cost of 160kB riscv rvc or arm7 thumb, 320kB on other risc arches, 240kB on x64.  Not sure if there's a better way to deal with this than adding AddCurrHeap/SubCurrHeap/Load/StoreWithCurrHeap instructions (ugly) or allowing access to the sp+2 register before stack_remove (potentially huge proof impact).

**Comment by myreen** [comment]
Yes, this should definitely be done! A quick look at `data_to_word` suggests that only `AddCurrHeap` and `SubCurrHeap` are needed. I guess the right thing to do is to add cases for those to `wordLang$exp` and `stackLang$prog`.

I'll have a go at starting to make this change.

**Comment by sorear** [comment]
I called it the ugly option because the difficulty compounds with better instruction selection.  Most of our non-riscv target architectures have some form of load or store with 2 address registers, now we suddenly need to allow one of those to be CurrHeap instead of a wordLang register.
