### ISSUE TITLE
use deep matches in translator

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#8]
The HOL examples directory now includes new technology (under `deep_matches`) for converting HOL case expressions into expressions based on a new `PMATCH` constant with an explicit, more easy-to-manipulate, semantics in HOL. We should investigate using this for the translation of case expressions into CakeML. An important potential advantage is that it is easier to do sophisticated simplification of `PMATCH` terms before translation (easier than simplifying case terms directly). It could speed up both the translator and the resulting CakeML code.

**Comment by xrchz** [comment]
Is this done now? The translator will correctly translate `PMATCH` if it is in the input term, but there is no automatic introduction of `PMATCH`. It's not obvious the latter is the translator's job though.

**Comment by myreen** [comment]
The translator's support for deep_matches is good enough for now. We can create new issues for PMATCH-related feature requests / bugs later.

**Comment by thtuerk** [comment]
You could just advice users to use ``PMATCH_INTRO_CONV``  on the input if they want to. This should be easy and gives control to the user. This translation already does some cleanup (combining rows, getting rid of ARB etc). For even better results (and much longer runtime), it could be combined with the simplification tools of the pattern-match lib. Moreover, you could consider adding a note about removing double binds and guards using the tools provided by the pattern match lib.

**Comment by myreen** [comment]
I like Thomas' view that control should be with the user here. The PMATCH case expressions are very well setup for this. I think it's best to have the HOL→CakeML translator just convert any PMATCH expression in a very direct way, as it currently does, but tell users about Thomas' library functions.
