### ISSUE TITLE
update explorer for new compiler

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#80]
The idea is still to be able to partially evaluate the compiler to see how it transforms various programs at different stages through compilation.

**Comment by xrchz** [comment]
Hi @tanyongkiam: what are your plans for this issue? @ajaysusarla may be interested in working on it (or generally on helpful things that don't require a lot of proof work), and I was wondering if we three could chat and make a plan that Partha could work on.

**Comment by tanyongkiam** [comment]
Sure, I have been distracted by other stuff. We should have a chat about this (maybe tomorrow at the CakeML Hangout?).

**Comment by xrchz** [comment]
I guess this is superseded by @myreen's undergrads' project. So shall we close it?

**Comment by xrchz** [comment]
I guess we can close it when the `explorer` branch is merged.

**Comment by xrchz** [comment]
Actually, I say close this when we can actually use it. I.e., a web or command line interface that works.

**Comment by xrchz** [comment]
There's a new explorer that works better, so we don't need this now.
