### ISSUE TITLE
parsing/proofs

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#81]
It would be nice if the proofs about the parser could be separated out from the definition, in a similar style to other parts of the compiler (the backend and inferencer for example). (Either that or we should reconsider this convention...)

The general principle is that one should be able to mostly see and understand just a definition of the compiler in the `compiler` directory, without having to think about its verification at all, and all the verification invariants and proofs live under `proofs` directories (or other special directories like `semantics`).  Basic proofs like termination proofs and simple syntactic properties of definitions can live alongside the definitions if that's more convenient.

**Comment by xrchz** [comment]
Is this done? (Relevant commits appear to be: ae7832567a8b2a78f906cb0fb6e1b6e8cfbf0d8e, c08c273bde3d512c85a53901d7c6bf196c56625c, f1b2c6fddb826cfd03d4a25836ccd0ff8d46789b)

**Comment by mn200** [comment]
Think so
