### ISSUE TITLE
Negative floating point literals are those of C

### ISSUE THREAD

**Issue by konrad-slind** [CakeML/cakeml#825]
The use of sscanf in the FFI to handle floating-point literal parsing means that ~42.0 in ML syntax gets translated to the wrong number.

val d = Double.fromString "~42.0";
val _ = print ("~42.0 ----> "^Double.toString d^"\n");

val d = Double.fromString "-42.0";
val _ = print ("-42.0 ----> "^Double.toString d^"\n");

**Comment by HeikoBecker** [comment]
Would you like  `Double.fromString` to  treat `~` like `-`?

**Comment by konrad-slind** [comment]
I think so. Should be like integer literal syntax. I noted in the Slack
chat that one would like

   ~(fromString s) = fromString (~s)

to hold.

**Comment by myreen** [comment]
Closed by PR #826
