### ISSUE TITLE
Compiler includes linebreaks inside string literals when computing locations for error messages

### ISSUE THREAD

**Issue by oskarabrahamsson** [CakeML/cakeml#830]
When reporting line numbers in errors, the parser--or possibly the machinery surrounding it--includes linebreaks found inside string literals. 

Here is an example file with an error on line 3:
```sml
(* foo.cml *)
val _ = "\n\n\n\n";
val _ = this_causes_an_error "foo";
```
But the compiler concerns line 7:
```
~ cake < foo.cml
### ERROR: type error
Undefined variable: this_causes_an_error at location starting at row 7 column 9, ending at row 7 column 28
```

This error is present in the latest version of the compiler currently available: https://github.com/CakeML/cakeml/releases/tag/v1535.

**Comment by mn200** [comment]
I think this is the lever giving incorrect line numbers to tokens, which then causes the type inference machinery to emit bad/incorrect messages. Thus, strictly, I think the parser has nothing to do with it.   But I'll have a look at what the machinery that adds line numbers is doing.

**Comment by oskarabrahamsson** [comment]
I think this is the culprit:
https://github.com/CakeML/cakeml/blob/master/semantics/lexer_funScript.sml#L78
`next_line` should be `next_loc 2`. I'll fix this later today.
