### ISSUE TITLE
Support type annotations

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#84]
Would be nice to add this feature to CakeML. Also see this thread for further motivation https://lists.cakeml.org/pipermail/users/2015-October/000066.html

**Comment by tanyongkiam** [comment]
It might be worth taking a closer look at the module system in general:

This does not type check either:

structure foo :> sig val x : int end = struct val x = 5 end;

(I think probably because undoing of type abbreviations is incorrectly applied / missing somewhere)

**Comment by xrchz** [comment]
probably something like this to fix the above bug (untested)
```
diff --git a/semantics/typeSystem.lem b/semantics/typeSystem.lem
index 049a44e..841a31b 100644
--- a/semantics/typeSystem.lem
+++ b/semantics/typeSystem.lem
@@ -723,7 +723,7 @@ sval : forall mn tenvT x t specs flat_tenvT cenv tenv fvs decls.
 check_freevars 0 fvs t &&
 type_specs mn tenvT specs decls flat_tenvT cenv tenv
 ==>
-type_specs mn tenvT (Sval x t :: specs) decls flat_tenvT cenv (tenv++[(x,(List.length fvs, type_subst (alistToFmap (List_extra.zipSameLength fvs (List.map Tvar_db (genlist (fun x -> x) (List.length fvs))))) t))])
+type_specs mn tenvT (Sval x t :: specs) decls flat_tenvT cenv (tenv++[(x,(List.length fvs, type_subst (alistToFmap (List_extra.zipSameLength fvs (List.map Tvar_db (genlist (fun x -> x) (List.length fvs))))) (type_name_subst tenvT t)))])
 
 and
```

**Comment by xrchz** [comment]
The problem mentioned above is possible more serious, and not to do with type abbreviations at all:
```
structure foo = struct val x = 5 end;
<type error>
```

**Comment by xrchz** [comment]
The attempted fix above, using `type_name_subst`, appears not to work.

**Comment by tanyongkiam** [comment]
That example runs fine on my version of the REPL and also the explorer
(which I assume got updated).

Did it occur after you added type_name_subst?

**Comment by xrchz** [comment]
Sorry: that was a false alarm - I had defined `foo` twice in one session. I am now rebuilding things in order to test whether `type_name_subst` works for the original example. (The explorer won't be updated until that works.)

**Comment by xrchz** [comment]
Scott and I are thinking of leaving this broken on version1, and just fixing it on master, since it looks like it might have various knock-on effects on the type soundness and inferencer proofs.

**Comment by xrchz** [comment]
@SOwens what is the status of this? I think I've seen a lot of work towards it recently.

**Comment by SOwens** [comment]
@theolaurent has been working on it. The inferencer completeness proof needs updating, as does the source_to_mod poof (but that should be trivial).

**Comment by xrchz** [comment]
@SOwens and now?

**Comment by SOwens** [comment]
The type annotations still can't contain type variables. But we can open a new issue if that becomes important.
