### ISSUE TITLE
remove context-dependence from ml_translatorLib

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#85]
Currently, the translator sometimes fails depending on the context (of definitions or of the parser) in which it is loaded. I think this is only due to parsing. The current workaround of redefining the `Parse` structure does not seem to always work. A more principled solution would be to build all requisite terms without using the parser, and to provide syntax functions for the theories whose terms the translator needs to make this expedient.

**Comment by mn200** [comment]
Redefining the `Parse` structure can fail if there are calls to other functions within the library source code that themselves depend on the global context of the parser. This can happen if you are proving goals using tactics from `Q` (these invoke the parser themselves). To get around this, it's possible to adjust the reference containing the current grammar, and to then put it back again.  Though hideous this *will* work until we become multi-threaded within a HOL session.
