### ISSUE TITLE
How to do floating point arithmetic

### ISSUE THREAD

**Issue by michael-roe** [CakeML/cakeml#893]
I couldn't figure out how to do floating point arithmetic in cakeml.

Double.fromString takes as input a string containing the text representation of a floating point value and returns a Word64 containing the IEEE 754 representation of the fp value. Ok, fine, that works.

But I can't then do arithmetic on this value. Double.+ seems to be expecting a different type.

I'm not sure if this is just a gap in the documentation or of something isn't working here.

> Double.+ Double.fromString("1") Double.fromString("1");
ERROR: Type mismatch between 14 -> 14 -> Word64.word and (string -> Word64.word) -> _0 at line 2

**Comment by oskarabrahamsson** [comment]
This is a known issue addressed by #892.
