### ISSUE TITLE
process_topdecs should avoid names user might use

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#925]
The current implementation of `process_topdecs` turns expressions in to A-normal form. In this process it introduces new temporary names. Annoyingly the names are often `a`, `b`, `c`, etc. which can shadow original names. This issue is about changing `process_topdecs` (more specifically `cfNormaliseLib.sml`) to not use names a user might have typed as concrete syntax.

Thanks to @arolle and @tanyongkiam for reporting this issue.

**Comment by myreen** [comment]
Closed by https://github.com/CakeML/cakeml/pull/926

**Comment by arolle** [comment]
Thanks!
