### ISSUE TITLE
Logical "&&" and "||" feature in Pancake

### ISSUE THREAD

**Issue by Kswin01** [CakeML/cakeml#935]
Having logical "and" and "or" for conditional statements in pancake would be a QoL improvement.

**Comment by Kswin01** [comment]
Yes, my apologies I was not aware this was added. I have just tested this and it seems to be working well

**Comment by IlmariReissumies** [comment]
As discussed with @Kswin01 in private correspondence though, the ones we have currently are bitwise not logical. While @Kswin01 can make do with them for now, it seems a silly restriction not to have logical and/or, so reopening.

**Comment by IlmariReissumies** [comment]
Fixed in #999
