### ISSUE TITLE
Support translation of bytes

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#98]
Although CakeML has a primitive byte (word8) type, the translator currently does not target it and cannot translate HOL functions over bytes. Adding this support might require adding more primitive operations over CakeML's bytes. Also, the design should be coordinate with any plans to support translation of words of other sizes.

**Comment by xrchz** [comment]
@myreen is this done, would you say? The translator does support `n2w` and `w2n` for bytes now. I think support for operations should come under #106.

**Comment by xrchz** [comment]
It still supports `i2w` and `w2i` for bytes too, right?

**Comment by myreen** [comment]
The translator supports `n2w`, `w2n`, `i2w`, `w2i` for bytes.
