### ISSUE TITLE
Initial program from translator

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#99]
As in https://lists.cakeml.org/private/dev/2016-January/001392.html

**Comment by xrchz** [comment]
Also see https://lists.cakeml.org/private/dev/2016-June/001638.html

**Comment by myreen** [comment]
@xrchz could you replace the old basis program with this one?

**Comment by xrchz** [comment]
@myreen I have attempted to remove the old basis program. The biggest users were in fact the cf and translator examples/demos/tutorials. I have not been able to update the cf examples to use the new basis program: could you take a look at that? See commit message above.

**Comment by xrchz** [comment]
Nice work! I think in general there should not be any unfolding, because usually we have a proper definition being translated. Those basis library wrapper functions are a special case: they are just there to wrap the abstract syntax primitives. I think the CF specs for the translated basis functions should be saved in basisProgramTheory after manually unfolding `plus_def` etc. for the ones that are simple wrappers.

**Comment by Armael** [comment]
Yes, sounds like a good solution. This should work nicely as cf tactics search first for a proper cf spec, before looking for a theorem from the translator.

**Comment by myreen** [comment]
Indeed, nice work!

As Ramana says, the wrappers are a silly side effect of the way the `basis` program is generated. I suggest that I update the way the translation works in `basisProgramScript` so that these wrapper functions are removed immediately after each translation in `basisProgramScript`.

**Comment by myreen** [comment]
Commit b88d525 removes the wrappers mentioned above.

**Comment by Armael** [comment]
And commit 51a161b765040da2159ae23c7504f5d744acea4b makes `characteristic/examples/*` compile again (with only very minor modifications).
